import { overview as dashboardOverview } from "./dashboard";
import { capabilities, setEntitlement } from "./modules";
import {
  cancelInvitation,
  deleteOrganization,
  inviteMember,
  joinLinkCreate,
  joinLinkPreview,
  joinLinkRedeem,
  joinLinkRevoke,
  leaveOrganization,
  management,
  removeMember,
  selection,
  updateMemberRole,
  updateOrganization,
} from "./organization";
import {
  addOrderItem,
  closeOrder,
  configuration,
  createArea,
  createTable,
  deleteArea,
  deleteDraftItem,
  deleteTable,
  kitchenBoard,
  bootstrap as restaurantBootstrap,
  sendToKitchen,
  tableDetail,
  updateArea,
  updateDraftItem,
  updateItemStatus,
  updateOrderMeta,
  updateTable,
} from "./restaurants";
import {
  cancel as cancelSale,
  create as createSale,
  list as listSales,
  detail as saleDetail,
} from "./sales";
import { get as getSettings, update as updateSettings } from "./settings";

export const router = {
  organization: {
    joinLinkPreview,
    joinLinkRedeem,
    selection,
    management,
    joinLinkCreate,
    joinLinkRevoke,
    inviteMember,
    cancelInvitation,
    updateMemberRole,
    removeMember,
    leaveOrganization,
    updateOrganization,
    deleteOrganization,
  },
  modules: {
    capabilities,
    setEntitlement,
  },
  settings: {
    get: getSettings,
    update: updateSettings,
  },
  dashboard: {
    overview: dashboardOverview,
  },
  sales: {
    list: listSales,
    detail: saleDetail,
    create: createSale,
    cancel: cancelSale,
  },
  restaurants: {
    bootstrap: restaurantBootstrap,
    tableDetail,
    addOrderItem,
    updateOrderMeta,
    updateDraftItem,
    deleteDraftItem,
    sendToKitchen,
    updateItemStatus,
    closeOrder,
    configuration,
    createArea,
    updateArea,
    deleteArea,
    createTable,
    updateTable,
    deleteTable,
    kitchenBoard,
  },
};
