import { drizzleZeroConfig } from "drizzle-zero";
import {
  account,
  invitation,
  invitationRelations,
  member,
  memberRelations,
  organization,
  organizationJoinLink,
  organizationJoinLinkRelations,
  organizationRelations,
  session,
  user,
  verification,
} from "./database/drizzle/schema/auth.schema";
import {
  creditAccount,
  creditAccountRelations,
  creditTransaction,
  creditTransactionRelations,
} from "./database/drizzle/schema/credit.schema";
import {
  customer,
  customerRelations,
} from "./database/drizzle/schema/customer.schema";
import { organizationModuleEntitlement } from "./database/drizzle/schema/feature.schema";
import {
  category,
  categoryRelations,
  inventoryMovement,
  inventoryMovementRelations,
  product,
  productIngredient,
  productIngredientRelations,
  productRelations,
} from "./database/drizzle/schema/inventory.schema";
import {
  pedido,
  pedidoItem,
  pedidoItemRelations,
  pedidoRelations,
} from "./database/drizzle/schema/orders.schema";
import {
  cashMovement,
  cashMovementRelations,
  shift,
  shiftClosure,
  shiftClosureRelations,
  shiftRelations,
} from "./database/drizzle/schema/pos.schema";
import {
  restaurantArea,
  restaurantAreaRelations,
  restaurantKitchenTicket,
  restaurantKitchenTicketLine,
  restaurantKitchenTicketLineRelations,
  restaurantKitchenTicketRelations,
  restaurantOrder,
  restaurantOrderItem,
  restaurantOrderItemModifier,
  restaurantOrderItemModifierRelations,
  restaurantOrderItemRelations,
  restaurantOrderRelations,
  restaurantTable,
  restaurantTableRelations,
} from "./database/drizzle/schema/restaurant.schema";
import {
  payment,
  paymentRelations,
  sale,
  saleItem,
  saleItemModifier,
  saleItemModifierRelations,
  saleItemRelations,
  saleRelations,
} from "./database/drizzle/schema/sales.schema";

const drizzleSchema = {
  account,
  cashMovement,
  cashMovementRelations,
  category,
  categoryRelations,
  creditAccount,
  creditAccountRelations,
  creditTransaction,
  creditTransactionRelations,
  customer,
  customerRelations,
  inventoryMovement,
  inventoryMovementRelations,
  invitation,
  invitationRelations,
  member,
  memberRelations,
  organization,
  organizationJoinLink,
  organizationJoinLinkRelations,
  organizationModuleEntitlement,
  organizationRelations,
  payment,
  paymentRelations,
  pedido,
  pedidoItem,
  pedidoItemRelations,
  pedidoRelations,
  product,
  productIngredient,
  productIngredientRelations,
  productRelations,
  restaurantArea,
  restaurantAreaRelations,
  restaurantKitchenTicket,
  restaurantKitchenTicketLine,
  restaurantKitchenTicketLineRelations,
  restaurantKitchenTicketRelations,
  restaurantOrder,
  restaurantOrderItem,
  restaurantOrderItemModifier,
  restaurantOrderItemModifierRelations,
  restaurantOrderItemRelations,
  restaurantOrderRelations,
  restaurantTable,
  restaurantTableRelations,
  sale,
  saleItem,
  saleItemModifier,
  saleItemModifierRelations,
  saleItemRelations,
  saleRelations,
  session,
  shift,
  shiftClosure,
  shiftClosureRelations,
  shiftRelations,
  user,
  verification,
} as const;

export default drizzleZeroConfig(drizzleSchema, {
  tables: {
    // better-auth persistence tables contain credentials/tokens and must never
    // be part of the browser-replicated Zero schema.
    account: false,
    session: false,
    verification: false,

    user: {
      id: true,
      name: true,
      email: true,
      emailVerified: true,
      image: true,
      createdAt: true,
      updatedAt: true,
      role: true,
    },
    organization: {
      id: true,
      name: true,
      slug: true,
      logo: true,
      createdAt: true,
      metadata: true,
    },
    member: {
      id: true,
      organizationId: true,
      userId: true,
      role: true,
      createdAt: true,
    },
    invitation: {
      id: true,
      organizationId: true,
      email: true,
      role: true,
      status: true,
      expiresAt: true,
      createdAt: true,
      inviterId: true,
    },
    organizationJoinLink: {
      id: true,
      organizationId: true,
      token: true,
      role: true,
      label: true,
      createdByUserId: true,
      createdAt: true,
      expiresAt: true,
      maxUses: true,
      useCount: true,
      lastUsedAt: true,
      lastUsedByUserId: true,
      revokedAt: true,
    },
    organizationModuleEntitlement: {
      id: true,
      organizationId: true,
      moduleKey: true,
      status: true,
      updatedByUserId: true,
      createdAt: true,
      updatedAt: true,
    },

    category: {
      id: true,
      organizationId: true,
      name: true,
      description: true,
      createdAt: true,
    },
    product: {
      id: true,
      organizationId: true,
      categoryId: true,
      name: true,
      sku: true,
      barcode: true,
      price: true,
      cost: true,
      taxRate: true,
      isModifier: true,
      isIngredient: true,
      trackInventory: true,
      stock: true,
      minStock: true,
      reorderQuantity: true,
      isFavorite: true,
      accountingTreatment: true,
      autoPayoutEnabled: true,
      autoPayoutPaymentMethod: true,
      deletedAt: true,
      createdAt: true,
    },
    productIngredient: {
      id: true,
      organizationId: true,
      productId: true,
      ingredientId: true,
      quantity: true,
      createdAt: true,
    },
    inventoryMovement: {
      id: true,
      organizationId: true,
      productId: true,
      userId: true,
      type: true,
      quantity: true,
      notes: true,
      createdAt: true,
    },

    customer: {
      id: true,
      organizationId: true,
      type: true,
      documentType: true,
      documentNumber: true,
      name: true,
      email: true,
      phone: true,
      address: true,
      city: true,
      taxRegime: true,
      deletedAt: true,
      createdAt: true,
      updatedAt: true,
    },

    shift: {
      id: true,
      organizationId: true,
      userId: true,
      terminalId: true,
      terminalName: true,
      status: true,
      startingCash: true,
      openedAt: true,
      closedAt: true,
      notes: true,
    },
    cashMovement: {
      id: true,
      organizationId: true,
      shiftId: true,
      type: true,
      paymentMethod: true,
      amount: true,
      description: true,
      sourceType: true,
      sourceSaleId: true,
      createdAt: true,
    },
    shiftClosure: {
      id: true,
      shiftId: true,
      paymentMethod: true,
      expectedAmount: true,
      actualAmount: true,
      difference: true,
    },

    sale: {
      id: true,
      organizationId: true,
      shiftId: true,
      customerId: true,
      userId: true,
      subtotal: true,
      taxAmount: true,
      discountAmount: true,
      totalAmount: true,
      passThroughSubtotal: true,
      passThroughTaxAmount: true,
      passThroughTotalAmount: true,
      status: true,
      createdAt: true,
    },
    saleItem: {
      id: true,
      saleId: true,
      organizationId: true,
      productId: true,
      quantity: true,
      unitPrice: true,
      subtotal: true,
      taxRate: true,
      taxAmount: true,
      discountAmount: true,
      totalAmount: true,
      accountingTreatment: true,
    },
    saleItemModifier: {
      id: true,
      saleItemId: true,
      organizationId: true,
      modifierProductId: true,
      quantity: true,
      unitPrice: true,
      subtotal: true,
    },
    payment: {
      id: true,
      organizationId: true,
      saleId: true,
      shiftId: true,
      method: true,
      reference: true,
      amount: true,
      appliedAmount: true,
      changeAmount: true,
      createdAt: true,
    },

    creditAccount: {
      id: true,
      organizationId: true,
      customerId: true,
      balance: true,
      interestRate: true,
      createdAt: true,
      updatedAt: true,
    },
    creditTransaction: {
      id: true,
      organizationId: true,
      creditAccountId: true,
      saleId: true,
      paymentId: true,
      type: true,
      amount: true,
      notes: true,
      createdAt: true,
    },

    restaurantArea: {
      id: true,
      organizationId: true,
      name: true,
      sortOrder: true,
      deletedAt: true,
      createdAt: true,
      updatedAt: true,
    },
    restaurantTable: {
      id: true,
      organizationId: true,
      areaId: true,
      name: true,
      seats: true,
      sortOrder: true,
      isActive: true,
      deletedAt: true,
      createdAt: true,
      updatedAt: true,
    },
    restaurantOrder: {
      id: true,
      organizationId: true,
      tableId: true,
      openedByUserId: true,
      closedByUserId: true,
      cancelledByUserId: true,
      saleId: true,
      orderNumber: true,
      status: true,
      guestCount: true,
      notes: true,
      createdAt: true,
      updatedAt: true,
      closedAt: true,
      cancelledAt: true,
      cancellationReason: true,
    },
    restaurantKitchenTicket: {
      id: true,
      organizationId: true,
      orderId: true,
      createdByUserId: true,
      kind: true,
      sequenceNumber: true,
      status: true,
      createdAt: true,
      updatedAt: true,
      printedAt: true,
    },
    restaurantKitchenTicketLine: {
      id: true,
      organizationId: true,
      kitchenTicketId: true,
      orderItemId: true,
      operation: true,
      productName: true,
      quantity: true,
      notes: true,
      previousQuantity: true,
      previousNotes: true,
      previousModifiersSnapshot: true,
      modifiersSnapshot: true,
      status: true,
      createdAt: true,
      updatedAt: true,
    },
    restaurantOrderItem: {
      id: true,
      organizationId: true,
      orderId: true,
      kitchenTicketId: true,
      productId: true,
      quantity: true,
      unitPrice: true,
      taxRate: true,
      discountAmount: true,
      accountingTreatment: true,
      notes: true,
      pendingCancellation: true,
      sentModifiersSnapshot: true,
      sentNotes: true,
      sentProductName: true,
      sentQuantity: true,
      status: true,
      createdAt: true,
      updatedAt: true,
      sentAt: true,
      readyAt: true,
      servedAt: true,
      cancelledAt: true,
    },
    restaurantOrderItemModifier: {
      id: true,
      organizationId: true,
      orderItemId: true,
      modifierProductId: true,
      quantity: true,
      unitPrice: true,
      createdAt: true,
    },

    pedido: {
      id: true,
      organizationId: true,
      customerId: true,
      saleId: true,
      acceptedByUserId: true,
      orderNumber: true,
      status: true,
      fulfillment: true,
      source: true,
      contactName: true,
      contactPhone: true,
      deliveryAddress: true,
      deliveryNotes: true,
      notes: true,
      subtotal: true,
      taxAmount: true,
      totalAmount: true,
      createdAt: true,
      updatedAt: true,
      closedAt: true,
    },
    pedidoItem: {
      id: true,
      organizationId: true,
      orderId: true,
      productId: true,
      quantity: true,
      unitPrice: true,
      taxRate: true,
      totalAmount: true,
      notes: true,
      createdAt: true,
    },
  },
});
