import readline from "node:readline/promises";
import { eq, sql } from "drizzle-orm";
import { drizzle } from "drizzle-orm/postgres-js";
import { seed } from "drizzle-seed";
import postgres from "postgres";
import { organization } from "@/database/drizzle/schema/auth.schema";
import { category, product } from "@/database/drizzle/schema/inventory.schema";

const databaseUrl = process.env.DATABASE_URL;
if (!databaseUrl) {
  throw new Error("DATABASE_URL environment variable is not set");
}

const client = postgres(databaseUrl);
const db = drizzle(client);

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
});

const CATEGORY_NAMES = [
  "Bebidas",
  "Alimentos",
  "Lácteos",
  "Carnes",
  "Pescados",
  "Frutas",
  "Verduras",
  "Panadería",
  "Congelados",
  "Snacks",
  "Bebidas Alcohólicas",
  "Limpieza",
  "Cuidado Personal",
  "Hogar",
  "Electrónica",
  "Ropa",
  "Accesorios",
  "Juguetes",
  "Mascotas",
  "Farmacia",
  "Papelería",
  "Ferretería",
  "Deportes",
  "Jardín",
  "Automotriz",
  "Bebés",
  "Belleza",
  "Café",
  "Té",
  "Jugos",
  "Gaseosas",
  "Cervezas",
  "Vinos",
  "Licores",
  "Quesos",
  "Embutidos",
  "Aves",
  "Res",
  "Cerdo",
  "Mariscos",
  "Arroz",
  "Pastas",
  "Legumbres",
  "Aceites",
  "Salsas",
  "Especias",
  "Harinas",
  "Azúcar",
  "Sal",
  "Miel",
  "Mermeladas",
  "Chocolate",
  "Galletas",
  "Helados",
  "Postres",
  "Pizzas",
  "Hamburguesas",
  "Comida Rápida",
  "Sushi",
  "Mexicana",
  "Italiana",
  "Asiática",
  "Vegana",
  "Orgánica",
  "Sin Gluten",
  "Sin Lactosa",
  "Desayuno",
  "Almuerzo",
  "Cena",
  "Bebidas Calientes",
  "Bebidas Frías",
  "Cócteles",
  "Cerveza Artesanal",
  "Vino Tinto",
  "Vino Blanco",
  "Whisky",
  "Ron",
  "Vodka",
  "Tequila",
  "Brandy",
  "Cognac",
  "Ginebra",
  "Champagne",
  "Espumante",
  "Sidra",
  "Sake",
  "Licuados",
  "Smoothies",
  "Agua",
  "Energéticas",
  "Isotónicas",
  "Refrescos",
  "Infusiones",
  "Mate",
  "Leche",
  "Yogur",
  "Crema",
  "Mantequilla",
  "Queso Fresco",
  "Queso Maduro",
  "Jamón",
  "Salchichas",
  "Tocino",
  "Mortadela",
  "Pollo",
  "Pavo",
  "Pato",
  "Cordero",
  "Ternera",
  "Costillas",
  "Chuletas",
  "Filetes",
  "Langostinos",
  "Camarones",
  "Pulpo",
  "Calamar",
  "Mejillones",
  "Almejas",
  "Ostras",
  "Atún",
  "Salmón",
  "Bacalao",
  "Sardinas",
  "Anchoas",
  "Trucha",
  "Lentejas",
  "Garbanzos",
  "Frijoles",
  "Habas",
  "Quinoa",
  "Avena",
  "Cebada",
  "Trigo",
  "Maíz",
  "Pan",
  "Tortillas",
  "Arepas",
  "Empanadas",
  "Pastelitos",
  "Tartas",
  "Croissants",
  "Donas",
  "Brownies",
  "Cupcakes",
  "Muffins",
  "Tortas",
  "Cheesecakes",
  "Flan",
  "Tiramisú",
  "Helado",
  "Sorbete",
  "Granizado",
  "Paletas",
  "Yogur Helado",
  "Conos",
  "Sandwich",
  "Wraps",
  "Burritos",
  "Tacos",
  "Nachos",
  "Quesadillas",
  "Enchiladas",
  "Fajitas",
  "Pasta",
  "Lasaña",
  "Risotto",
  "Gnocchi",
  "Ravioli",
  "Espaguetis",
  "Macarrones",
  "Fettuccine",
  "Penne",
  "Rigatoni",
  "Tagliatelle",
  "Canelones",
  "Carpaccio",
  "Bruschetta",
  "Antipasti",
  "Provolone",
  "Mozzarella",
  "Parmesano",
  "Gouda",
  "Cheddar",
  "Brie",
  "Camembert",
  "Roquefort",
  "Feta",
  "Havarti",
  "Edam",
  "Manchego",
  "Pecorino",
  "Asiago",
  "Gruyère",
  "Emmental",
  "Taleggio",
  "Fontina",
  "Stracciatella",
  "Ricotta",
  "Mascarpone",
  "Burrata",
  "Halloumi",
  "Paneer",
  "Cottage",
  "Crema Batida",
  "Natilla",
  "Arroz con Leche",
  "Champurrado",
  "Atole",
  "Chilate",
  "Pozol",
  "Tepache",
  "Agua Fresca",
  "Horchata",
  "Jamaica",
  "Tamarindo",
  "Chía",
  "Linaza",
  "Almendra",
  "Coco",
  "Soya",
  "Avena",
  "Arroz",
  "Quinoa",
  "Espelta",
  "Kamut",
  "Centeno",
  "Sorgo",
  "Mijo",
  "Teff",
  "Amaranto",
  "Chía",
  "Semillas",
  "Nueces",
  "Almendras",
  "Avellanas",
  "Pistachos",
  "Nueces de Macadamia",
  "Anacardos",
  "Piñones",
  "Castañas",
  "Pecanas",
  "Nueces de Brasil",
  "Cacahuetes",
  "Passas",
  "Dátiles",
  "Higos",
  "Ciruelas",
  "Albaricoques",
  "Melocotones",
  "Nectarinas",
  "Cerezas",
  "Manzanas",
  "Peras",
  "Uvas",
  "Naranjas",
  "Mandarinas",
  "Limones",
  "Limas",
  "Pomelos",
  "Toronjas",
  "Kiwis",
  "Plátanos",
  "Mangos",
  "Papayas",
  "Piñas",
  "Cocos",
  "Granadas",
  "Frambuesas",
  "Moras",
  "Arándanos",
  "Grosellas",
  "Mirtilos",
  "Fresas",
  "Zarzamoras",
  "Moras Azules",
  "Cranberries",
  "Goji",
  "Acai",
  "Noni",
  "Mangostán",
  "Rambután",
  "Lichi",
  "Longan",
  "Durian",
  "Jackfruit",
  "Guayaba",
  "Feijoa",
  "Tamarillo",
  "Physalis",
  "Capulin",
  "Zapote",
  "Mamey",
  "Chirimoya",
  "Lúcuma",
  "Camu Camu",
  "Aguaje",
  "Açaí",
  "Cupuaçu",
  "Guaraná",
  "Yerba Mate",
  "Jabuticaba",
  "Pitanga",
  "Acerola",
  "Caju",
  "Maracuyá",
  "Granadilla",
  "Curuba",
  "Borojó",
  "Níspero",
  "Membrillo",
  "Endrina",
  "Serba",
  "Sauco",
  "Rosa Mosqueta",
  "Espinacas",
  "Acelgas",
  "Espinacas de Nueva Zelanda",
  "Berros",
  "Rúcula",
  "Escarola",
  "Radicchio",
  "Endibias",
  "Achicoria",
  "Lechugas",
  "Repollo",
  "Col",
  "Brócoli",
  "Coliflor",
  "Romanescu",
  "Kohlrabi",
  "Berza",
  "Colinabo",
  "Rábano",
  "Nabo",
  "Zanahoria",
  "Apio",
  "Puerro",
  "Cebolla",
  "Ajo",
  "Chalota",
  "Echalote",
  "Patata",
  "Papa",
  "Batata",
  "Yuca",
  "Ñame",
  "Oca",
  "Mashua",
  "Arracacha",
  "Jícama",
  "Camote",
  "Zapallo",
  "Calabaza",
  "Zucchini",
  "Calabacín",
  "Pepino",
  "Tomate",
  "Jitomate",
  "Pimiento",
  "Ají",
  "Chile",
  "Berenjena",
  "Alcachofa",
  "Espárrago",
  "Cardo",
  "Hinojo",
  "Calabaza Butternut",
  "Calabaza Spaghetti",
  "Calabaza Acorn",
  "Calabaza Kabocha",
  "Calabaza Delicata",
  "Calabaza Hubbard",
  "Calabaza Pattypan",
  "Calabaza Crookneck",
  "Calabaza Straightneck",
  "Calabaza Calabaza",
  "Calabaza Calabacita",
  "Judías Verdes",
  "Ejotes",
  "Chauchas",
  "Habichuelas",
  "Lentejas",
  "Garbanzos",
  "Frijoles Negros",
  "Frijoles Rojos",
  "Frijoles Blancos",
  "Frijoles Pintos",
  "Frijoles Cargamanto",
  "Frijoles Cranberry",
  "Frijoles de Soja",
  "Edamame",
  "Tofu",
  "Tempeh",
  "Seitan",
  "Natto",
  "Miso",
  "Salsa de Soja",
  "Tamari",
  "Teriyaki",
  "Oyster Sauce",
  "Hoisin",
  "Sriracha",
  "Tabasco",
  "Salsa Valentina",
  "Salsa Cholula",
  "Salsa Tapatío",
  "Salsa Verde",
  "Salsa Roja",
  "Salsa de Chile de Árbol",
  "Salsa de Chile Guajillo",
  "Salsa de Chile Ancho",
  "Salsa de Chipotle",
  "Salsa de Habanero",
  "Salsa de Jalapeño",
  "Salsa de Poblano",
  "Salsa de Pasilla",
  "Salsa de Cascabel",
  "Salsa de Morita",
  "Salsa de Mulato",
  "Salsa de Serrano",
  "Salsa de Chile Verde",
  "Salsa de Chile Colorado",
  "Salsa Ranchera",
  "Salsa Criolla",
  "Salsa Golf",
  "Salsa Peruana",
  "Salsa de Rocoto",
  "Salsa de Ají Amarillo",
  "Salsa de Ají Panca",
  "Salsa de Ají Limo",
  "Salsa Huancaína",
  "Salsa de Ocopa",
  "Salsa de Tallarín",
  "Salsa de Papa a la Huancaína",
  "Salsa de Anticuchos",
  "Salsa de Pollo a la Brasa",
  "Salsa de Lomo Saltado",
  "Salsa de Causa Limeña",
  "Salsa de Ceviche",
  "Salsa de Tiradito",
  "Salsa de Pulpo a la Gallega",
  "Salsa de Fabada",
  "Salsa de Cocido",
  "Salsa de Callos",
  "Salsa de Paella",
  "Salsa de Fideuá",
  "Salsa de Gazpacho",
  "Salsa de Salmorejo",
  "Salsa de Ajoblanco",
  "Salsa de Porra",
  "Salsa de Migas",
  "Salsa de Patatas Bravas",
  "Salsa de Tortilla Española",
  "Salsa de Croquetas",
  "Salsa de Jamón Ibérico",
  "Salsa de Chorizo",
  "Salsa de Morcilla",
  "Salsa de Butifarra",
  "Salsa de Sobrasada",
  "Salsa de Longaniza",
  "Salsa de Salchichón",
  "Salsa de Fuet",
  "Salsa de Cecina",
  "Salsa de Jamón Serrano",
  "Salsa de Paletilla",
  "Salsa de Lomo Embuchado",
  "Salsa de Panceta",
  "Salsa de Tocino",
  "Salsa de Tocineta",
  "Salsa de Bacon",
  "Salsa de Pancetta",
  "Salsa de Guanciale",
  "Salsa de Speck",
  "Salsa de Prosciutto",
  "Salsa de Jamón de Parma",
  "Salsa de Jamón de Bayona",
  "Salsa de Jamón de Teruel",
  "Salsa de Jamón de Trevélez",
  "Salsa de Jamón de Jabugo",
  "Salsa de Jamón de Guijuelo",
  "Salsa de Jamón de Los Pedroches",
  "Salsa de Jamón de Córdoba",
  "Salsa de Jamón de Huelva",
  "Salsa de Jamón de Cáceres",
  "Salsa de Jamón de Salamanca",
  "Salsa de Jamón de Segovia",
  "Salsa de Jamón de Ávila",
  "Salsa de Jamón de Zamora",
  "Salsa de Jamón de León",
  "Salsa de Jamón de Burgos",
  "Salsa de Jamón de Palencia",
  "Salsa de Jamón de Valladolid",
];

const PRODUCT_NAMES = [
  "Refresco de Cola",
  "Gaseosa de Limón",
  "Gaseosa de Naranja",
  "Gaseosa de Uva",
  "Agua Mineral",
  "Agua con Gas",
  "Jugo de Naranja",
  "Jugo de Manzana",
  "Jugo de Piña",
  "Jugo de Mango",
  "Jugo de Fresa",
  "Leche Entera",
  "Leche Descremada",
  "Yogur Natural",
  "Yogur de Fresa",
  "Queso Fresco",
  "Queso Cheddar",
  "Queso Mozzarella",
  "Mantequilla",
  "Crema de Leche",
  "Pan de Molde",
  "Pan Integral",
  "Pan de Centeno",
  "Croissant",
  "Baguette",
  "Rosca de Pan",
  "Galletas de Chocolate",
  "Galletas de Avena",
  "Galletas Saladas",
  "Pastel de Chocolate",
  "Pastel de Vainilla",
  "Muffin de Arándanos",
  "Donut Glaseado",
  "Arroz Blanco",
  "Arroz Integral",
  "Pasta Espagueti",
  "Pasta Penne",
  "Fideos de Huevo",
  "Harina de Trigo",
  "Harina de Maíz",
  "Aceite Vegetal",
  "Aceite de Oliva",
  "Vinagre Blanco",
  "Vinagre de Manzana",
  "Salsa de Tomate",
  "Salsa de Soya",
  "Mayonesa",
  "Mostaza",
  "Ketchup",
  "Sal Marina",
  "Azúcar Blanca",
  "Azúcar Morena",
  "Miel Natural",
  "Café Molido",
  "Café Instantáneo",
  "Té Negro",
  "Té Verde",
  "Chocolate en Polvo",
  "Cereal de Maíz",
  "Cereal de Avena",
  "Avena en Hojuelas",
  "Mermelada de Fresa",
  "Mermelada de Naranja",
  "Mantequilla de Maní",
  "Nutella",
  "Gelatina de Fresa",
  "Flan de Vainilla",
  "Helado de Vainilla",
  "Helado de Chocolate",
  "Helado de Fresa",
  "Papas Fritas",
  "Nachos",
  "Palomitas de Maíz",
  "Maní Salado",
  "Barra de Granola",
  "Chicle de Menta",
  "Caramelo de Frutas",
  "Chocolate con Almendras",
  "Chocolate Blanco",
  "Jabón de Baño",
  "Shampoo Hidratante",
  "Acondicionador",
  "Crema Dental",
  "Desodorante",
  "Papel Higiénico",
  "Servilletas",
  "Detergente Líquido",
  "Suavizante de Ropa",
  "Limpia Vidrios",
  "Desinfectante",
  "Esponja de Cocina",
  "Bolsa de Basura",
  "Pilas AA",
  "Pilas AAA",
  "Bombillas LED",
  "Cinta Adhesiva",
  "Tijeras de Oficina",
  "Cuaderno de Rayas",
  "Lápiz de Grafito",
  "Bolígrafo Azul",
  "Marcador Permanente",
  "Goma de Borrar",
  "Regla de 30cm",
  "Pegamento en Barra",
  "Papel de Impresora",
  "Sobre Manila",
  "Carpeta de Archivo",
  "Clip Metálico",
  "Grapadora",
  "Grapas",
  "Post-it",
  "Calculadora Básica",
  "Agua de Rosas",
  "Crema Hidratante",
  "Protector Solar",
  "Balsamo Labial",
  "Shampoo Anticaspa",
  "Acondicionador Reparador",
  "Gel de Ducha",
  "Jabón Líquido",
  "Toallas Húmedas",
  "Pañales Talla M",
  "Pañales Talla G",
  "Leche de Fórmula",
  "Biberón",
  "Chupete",
  "Crema para Pañal",
  "Talco para Bebé",
  "Shampoo para Bebé",
  "Jabón para Bebé",
  "Toallitas para Bebé",
  "Galletas para Bebé",
  "Puré de Manzana",
  "Puré de Pera",
  "Puré de Plátano",
  "Jugo para Niños",
  "Leche en Polvo",
  "Yogur para Niños",
  "Queso para Niños",
  "Cereal para Niños",
  "Jabón para Niños",
  "Shampoo para Niños",
  " Pasta de Dientes para Niños",
  "Cepillo de Dientes para Niños",
  "Galletas de Arroz",
  "Galletas de Maíz",
  "Chitos de Queso",
  "Doritos Nacho",
  "Cheetos",
  "Galletas Oreo",
  "Galletas María",
  "Galletas de Vainilla",
  "Galletas de Chocolate",
  "Galletas de Mantequilla",
  "Galletas de Coco",
  "Galletas de Limón",
  "Galletas de Naranja",
  "Galletas de Fresa",
  "Galletas de Arándanos",
  "Galletas de Almendra",
  "Galletas de Nuez",
  "Galletas de Avena",
  "Galletas Integrales",
  "Galletas de Salvado",
  "Galletas de Semillas",
  "Galletas de Leche",
  "Galletas de Miel",
  "Galletas de Canela",
  "Galletas de Jengibre",
  "Galletas de Especias",
  "Galletas de Navidad",
  "Galletas de Pascua",
  "Galletas de Halloween",
  "Galletas de San Valentín",
  "Galletas de Cumpleaños",
  "Galletas de Boda",
  "Galletas de Bautizo",
  "Galletas de Comunión",
  "Galletas de Graduación",
  "Galletas de Aniversario",
  "Galletas de Jubilación",
  "Galletas de Navidad",
  "Galletas de Año Nuevo",
  "Galletas de Pascua",
  "Galletas de Halloween",
  "Galletas de San Valentín",
  "Galletas de Día de la Madre",
  "Galletas de Día del Padre",
  "Galletas de Día del Niño",
  "Galletas de Día de los Enamorados",
  "Galletas de Día de los Muertos",
  "Galletas de Día de la Independencia",
  "Galletas de Día de la Raza",
  "Galletas de Día de Acción de Gracias",
  "Galletas de Día del Trabajo",
  "Galletas de Día de la Tierra",
  "Galletas de Día del Medio Ambiente",
  "Galletas de Día de la Mujer",
  "Galletas de Día del Hombre",
  "Galletas de Día de la Familia",
  "Galletas de Día de los Abuelos",
  "Galletas de Día de los Tíos",
  "Galletas de Día de los Primos",
  "Galletas de Día de los Amigos",
  "Galletas de Día de los Vecinos",
  "Galletas de Día de los Compañeros",
  "Galletas de Día de los Colegas",
  "Galletas de Día de los Compañeros de Trabajo",
  "Galletas de Día de los Compañeros de Estudio",
  "Galletas de Día de los Compañeros de Equipo",
  "Galletas de Día de los Compañeros de Proyecto",
  "Galletas de Día de los Compañeros de Clase",
  "Galletas de Día de los Compañeros de Universidad",
  "Galletas de Día de los Compañeros de Escuela",
  "Galletas de Día de los Compañeros de Instituto",
  "Galletas de Día de los Compañeros de Academia",
  "Galletas de Día de los Compañeros de Curso",
  "Galletas de Día de los Compañeros de Taller",
  "Galletas de Día de los Compañeros de Seminario",
  "Galletas de Día de los Compañeros de Congreso",
  "Galletas de Día de los Compañeros de Conferencia",
  "Galletas de Día de los Compañeros de Reunión",
  "Galletas de Día de los Compañeros de Encuentro",
  "Galletas de Día de los Compañeros de Evento",
  "Galletas de Día de los Compañeros de Celebración",
  "Galletas de Día de los Compañeros de Fiesta",
  "Galletas de Día de los Compañeros de Reunión Social",
  "Galletas de Día de los Compañeros de Cena",
  "Galletas de Día de los Compañeros de Almuerzo",
  "Galletas de Día de los Compañeros de Desayuno",
  "Galletas de Día de los Compañeros de Merienda",
  "Galletas de Día de los Compañeros de Brunch",
  "Galletas de Día de los Compañeros de Picnic",
  "Galletas de Día de los Compañeros de Barbacoa",
  "Galletas de Día de los Compañeros de Parrillada",
  "Galletas de Día de los Compañeros de Asado",
  "Galletas de Día de los Compañeros de Fogata",
  "Galletas de Día de los Compañeros de Camping",
  "Galletas de Día de los Compañeros de Excursión",
  "Galletas de Día de los Compañeros de Viaje",
  "Galletas de Día de los Compañeros de Turismo",
  "Galletas de Día de los Compañeros de Vacaciones",
  "Galletas de Día de los Compañeros de Escapada",
  "Galletas de Día de los Compañeros de Fin de Semana",
  "Galletas de Día de los Compañeros de Puente",
  "Galletas de Día de los Compañeros de Festivo",
  "Galletas de Día de los Compañeros de Feriado",
  "Galletas de Día de los Compañeros de Carnaval",
  "Galletas de Día de los Compañeros de Feria",
  "Galletas de Día de los Compañeros de Romería",
  "Galletas de Día de los Compañeros de Procesión",
  "Galletas de Día de los Compañeros de Verbena",
  "Galletas de Día de los Compañeros de Festival",
  "Galletas de Día de los Compañeros de Concierto",
  "Galletas de Día de los Compañeros de Espectáculo",
  "Galletas de Día de los Compañeros de Función",
  "Galletas de Día de los Compañeros de Representación",
  "Galletas de Día de los Compañeros de Obra",
  "Galletas de Día de los Compañeros de Teatro",
  "Galletas de Día de los Compañeros de Danza",
  "Galletas de Día de los Compañeros de Música",
  "Galletas de Día de los Compañeros de Ópera",
  "Galletas de Día de los Compañeros de Ballet",
  "Galletas de Día de los Compañeros de Zarzuela",
  "Galletas de Día de los Compañeros de Musical",
  "Galletas de Día de los Compañeros de Revista",
  "Galletas de Día de los Compañeros de Cabaret",
  "Galletas de Día de los Compañeros de Circo",
  "Galletas de Día de los Compañeros de Magia",
  "Galletas de Día de los Compañeros de Humor",
  "Galletas de Día de los Compañeros de Monólogo",
  "Galletas de Día de los Compañeros de Stand-up",
  "Galletas de Día de los Compañeros de Impro",
  "Galletas de Día de los Compañeros de Comedia",
  "Galletas de Día de los Compañeros de Drama",
  "Galletas de Día de los Compañeros de Tragedia",
  "Galletas de Día de los Compañeros de Suspense",
  "Galletas de Día de los Compañeros de Terror",
  "Galletas de Día de los Compañeros de Misterio",
  "Galletas de Día de los Compañeros de Aventura",
  "Galletas de Día de los Compañeros de Acción",
  "Galletas de Día de los Compañeros de Ciencia Ficción",
  "Galletas de Día de los Compañeros de Fantasía",
  "Galletas de Día de los Compañeros de Animación",
  "Galletas de Día de los Compañeros de Documental",
  "Galletas de Día de los Compañeros de Cortometraje",
  "Galletas de Día de los Compañeros de Largometraje",
  "Galletas de Día de los Compañeros de Serie",
  "Galletas de Día de los Compañeros de Temporada",
  "Galletas de Día de los Compañeros de Capítulo",
  "Galletas de Día de los Compañeros de Episodio",
  "Galletas de Día de los Compañeros de Piloto",
  "Galletas de Día de los Compañeros de Spin-off",
  "Galletas de Día de los Compañeros de Remake",
  "Galletas de Día de los Compañeros de Adaptación",
  "Galletas de Día de los Compañeros de Secuela",
  "Galletas de Día de los Compañeros de Precuela",
  "Galletas de Día de los Compañeros de Interprecuela",
  "Galletas de Día de los Compañeros de Cuarta",
  "Galletas de Día de los Compañeros de Quinta",
  "Galletas de Día de los Compañeros de Sexta",
  "Galletas de Día de los Compañeros de Séptima",
  "Galletas de Día de los Compañeros de Octava",
  "Galletas de Día de los Compañeros de Novena",
  "Galletas de Día de los Compañeros de Décima",
  "Galletas de Día de los Compañeros de Undécima",
  "Galletas de Día de los Compañeros de Duodécima",
  "Galletas de Día de los Compañeros de Decimotercera",
  "Galletas de Día de los Compañeros de Decimocuarta",
  "Galletas de Día de los Compañeros de Decimoquinta",
  "Galletas de Día de los Compañeros de Decimosexta",
  "Galletas de Día de los Compañeros de Decimoséptima",
  "Galletas de Día de los Compañeros de Decimoctava",
  "Galletas de Día de los Compañeros de Decimonovena",
  "Galletas de Día de los Compañeros de Vigésima",
  "Galletas de Día de los Compañeros de Vigésima Primera",
  "Galletas de Día de los Compañeros de Vigésima Segunda",
  "Galletas de Día de los Compañeros de Vigésima Tercera",
  "Galletas de Día de los Compañeros de Vigésima Cuarta",
  "Galletas de Día de los Compañeros de Vigésima Quinta",
  "Galletas de Día de los Compañeros de Vigésima Sexta",
  "Galletas de Día de los Compañeros de Vigésima Séptima",
  "Galletas de Día de los Compañeros de Vigésima Octava",
  "Galletas de Día de los Compañeros de Vigésima Novena",
  "Galletas de Día de los Compañeros de Trigésima",
  "Galletas de Día de los Compañeros de Cuadragésima",
  "Galletas de Día de los Compañeros de Quincuagésima",
  "Galletas de Día de los Compañeros de Sexagésima",
  "Galletas de Día de los Compañeros de Septuagésima",
  "Galletas de Día de los Compañeros de Octogésima",
  "Galletas de Día de los Compañeros de Nonagésima",
  "Galletas de Día de los Compañeros de Centésima",
  "Galletas de Día de los Compañeros de Milésima",
  "Galletas de Día de los Compañeros de Millonésima",
  "Galletas de Día de los Compañeros de Billonésima",
  "Galletas de Día de los Compañeros de Trillonésima",
  "Galletas de Día de los Compañeros de Cuadrillonésima",
  "Galletas de Día de los Compañeros de Quintillonésima",
  "Galletas de Día de los Compañeros de Sextillonésima",
  "Galletas de Día de los Compañeros de Septillonésima",
  "Galletas de Día de los Compañeros de Octillonésima",
  "Galletas de Día de los Compañeros de Nonillonésima",
  "Galletas de Día de los Compañeros de Decillonésima",
  "Galletas de Día de los Compañeros de Undecillonésima",
  "Galletas de Día de los Compañeros de Duodecillonésima",
  "Galletas de Día de los Compañeros de Tredecillonésima",
  "Galletas de Día de los Compañeros de Cuatordecillonésima",
  "Galletas de Día de los Compañeros de Quindecillonésima",
  "Galletas de Día de los Compañeros de Sexdecillonésima",
  "Galletas de Día de los Compañeros de Septendecillonésima",
  "Galletas de Día de los Compañeros de Octodecillonésima",
  "Galletas de Día de los Compañeros de Novendecillonésima",
  "Galletas de Día de los Compañeros de Vigintillonésima",
];

async function main() {
  let selectedOrg: typeof organization.$inferSelect | undefined;

  const args = process.argv.slice(2);
  const orgIdArg = args
    .find((arg) => arg.startsWith("--org-id="))
    ?.split("=")[1];

  if (orgIdArg) {
    const orgRows = await db
      .select()
      .from(organization)
      .where(eq(organization.id, orgIdArg))
      .limit(1);
    const org = orgRows[0];
    if (!org) {
      console.error(`[ERROR] Organization with id "${orgIdArg}" not found.`);
      process.exit(1);
    }
    selectedOrg = org;
    console.log(
      `[INFO] Using organization from --org-id flag: ${selectedOrg.name}`
    );
  } else {
    console.log("[INFO] Fetching organizations...\n");

    const orgs = await db.select().from(organization);
    if (orgs.length === 0) {
      console.error("[ERROR] No organizations found in the database.");
      console.log(
        "[HINT] Please create an organization first via the app UI or API."
      );
      process.exit(1);
    }

    console.log("Select an organization:");
    for (const [i, org] of orgs.entries()) {
      console.log(`  [${i}] ${org.name} (id: ${org.id})`);
    }

    const answer = await rl.question("\nEnter number: ");
    const index = Number.parseInt(answer, 10);
    if (Number.isNaN(index) || index < 0 || index >= orgs.length) {
      console.error("[ERROR] Invalid selection.");
      process.exit(1);
    }

    selectedOrg = orgs[index];
    console.log(`\n[INFO] Selected organization: ${selectedOrg.name}`);
  }

  console.log("[INFO] Fetching categories...");
  const existingCategories = await db
    .select()
    .from(category)
    .where(eq(category.organizationId, selectedOrg.id));

  const categoryIds: string[] = existingCategories.map((c) => c.id);
  const existingCategoryNames = new Set(existingCategories.map((c) => c.name));
  const missingCategories = CATEGORY_NAMES.filter(
    (name) => !existingCategoryNames.has(name)
  );

  if (missingCategories.length > 0) {
    console.log(
      `[INFO] Creating ${missingCategories.length} missing categories...`
    );

    for (const name of missingCategories) {
      const result = await db
        .insert(category)
        .values({
          id: crypto.randomUUID(),
          organizationId: selectedOrg.id,
          name,
          description: null,
          createdAt: new Date(),
        })
        .returning();
      categoryIds.push(result[0].id);
    }
  } else {
    console.log("[INFO] All categories already exist.");
  }

  console.log(`[INFO] Created ${categoryIds.length} categories.`);

  // Seed 1000 products
  console.log("[INFO] Seeding 1000 products...");
  await seed(db, { product }).refine((f) => ({
    product: {
      count: 1000,
      columns: {
        id: f.uuid(),
        organizationId: f.default({ defaultValue: selectedOrg.id }),
        categoryId: f.valuesFromArray({ values: categoryIds }),
        name: f.valuesFromArray({ values: PRODUCT_NAMES }),
        sku: f.default({ defaultValue: null }),
        barcode: f.default({ defaultValue: null }),
        price: f.int({ minValue: 5000, maxValue: 500_000 }),
        cost: f.int({ minValue: 1000, maxValue: 300_000 }),
        taxRate: f.valuesFromArray({ values: [0, 5, 19] }),
        isModifier: f.default({ defaultValue: false }),
        trackInventory: f.default({ defaultValue: true }),
        stock: f.int({ minValue: 0, maxValue: 500 }),
        isFavorite: f.boolean(),
        deletedAt: f.default({ defaultValue: null }),
        createdAt: f.default({ defaultValue: new Date() }),
      },
    },
  }));

  const finalProducts = await db
    .select({ count: sql<number>`count(*)` })
    .from(product)
    .where(eq(product.organizationId, selectedOrg.id));

  console.log(
    `[SUCCESS] Organization now has ${finalProducts[0].count} products total.`
  );
  console.log("[SUCCESS] Done!");
}

main()
  .then(() => rl.close())
  .catch((err) => {
    console.error(err);
    rl.close();
    process.exit(1);
  });
