import { eq, sql } from "drizzle-orm";
import { drizzle } from "drizzle-orm/libsql";
import { seed } from "drizzle-seed";
import { createClient } from "@libsql/client";
import readline from "node:readline/promises";
import { category, product } from "../database/drizzle/schema/inventory.schema";
import { organization } from "../database/drizzle/schema/auth.schema";

const databaseUrl = process.env.DATABASE_URL;
if (!databaseUrl) {
	throw new Error("DATABASE_URL environment variable is not set");
}

const client = createClient({
	url: databaseUrl,
	authToken: process.env.DATABASE_AUTH_TOKEN,
});

const db = drizzle(client);

const rl = readline.createInterface({
	input: process.stdin,
	output: process.stdout,
});

const CATEGORY_NAMES = [
	"Bebidas",
	"Alimentos",
	"Lácteos",
	"Carnes",
	"Pescados",
	"Frutas",
	"Verduras",
	"Panadería",
	"Congelados",
	"Snacks",
	"Bebidas Alcohólicas",
	"Limpieza",
	"Cuidado Personal",
	"Hogar",
	"Electrónica",
	"Ropa",
	"Accesorios",
	"Juguetes",
	"Mascotas",
	"Farmacia",
	"Papelería",
	"Ferretería",
	"Deportes",
	"Jardín",
	"Automotriz",
	"Bebés",
	"Belleza",
	"Café",
	"Té",
	"Jugos",
	"Gaseosas",
	"Cervezas",
	"Vinos",
	"Licores",
	"Quesos",
	"Embutidos",
	"Aves",
	"Res",
	"Cerdo",
	"Mariscos",
	"Arroz",
	"Pastas",
	"Legumbres",
	"Aceites",
	"Salsas",
	"Especias",
	"Harinas",
	"Azúcar",
	"Sal",
	"Miel",
	"Mermeladas",
	"Chocolate",
	"Galletas",
	"Helados",
	"Postres",
	"Pizzas",
	"Hamburguesas",
	"Comida Rápida",
	"Sushi",
	"Mexicana",
	"Italiana",
	"Asiática",
	"Vegana",
	"Orgánica",
	"Sin Gluten",
	"Sin Lactosa",
	"Desayuno",
	"Almuerzo",
	"Cena",
	"Bebidas Calientes",
	"Bebidas Frías",
	"Cócteles",
	"Cerveza Artesanal",
	"Vino Tinto",
	"Vino Blanco",
	"Whisky",
	"Ron",
	"Vodka",
	"Tequila",
	"Gin",
	"Cigarrillos",
	"Dulces",
	"Chocolates",
	"Chicles",
	"Nueces",
	"Frutos Secos",
	"Semillas",
	"Granola",
	"Yogurt",
	"Mantequilla",
	"Crema",
	"Leche",
	"Huevos",
	"Pan",
	"Tortillas",
	"Arepas",
	"Empanadas",
	"Pasteles",
];

const PRODUCT_NAMES = [
	"Agua sin gas 500ml",
	"Agua con gas 500ml",
	"Coca-Cola 350ml",
	"Coca-Cola 1.5L",
	"Pepsi 350ml",
	"Sprite 350ml",
	"Fanta Naranja 350ml",
	"Jugo de Naranja 1L",
	"Jugo de Manzana 1L",
	"Jugo de Uva 500ml",
	"Jugo de Mango 500ml",
	"Leche Entera 1L",
	"Leche Descremada 1L",
	"Yogurt Natural 500g",
	"Yogurt de Fresa 500g",
	"Queso Mozzarella 250g",
	"Queso Cheddar 250g",
	"Queso Parmesano 100g",
	"Mantequilla 250g",
	"Crema de Leche 250ml",
	"Huevos Blancos x12",
	"Huevos Rojos x12",
	"Pan Blanco",
	"Pan Integral",
	"Pan de Avena",
	"Croissant",
	"Baguette",
	"Donut Glaseado",
	"Muffin de Arándanos",
	"Galletas de Chocolate",
	"Galletas de Vainilla",
	"Galletas Saladas",
	"Chips de Papa",
	"Chips de Plátano",
	"Maní Salado",
	"Maní Tostado",
	"Almendras 100g",
	"Nueces 100g",
	"Pasas 100g",
	"Chocolate en Barra",
	"Chocolate con Leche",
	"Chocolate Blanco",
	"Helado de Vainilla",
	"Helado de Chocolate",
	"Helado de Fresa",
	"Pizza Margarita",
	"Pizza Pepperoni",
	"Hamburguesa Clásica",
	"Hamburguesa con Queso",
	"Hot Dog",
	"Sandwich de Pollo",
	"Sandwich de Jamón y Queso",
	"Wrap de Pollo",
	"Taco de Carne",
	"Taco de Pollo",
	"Burrito de Carne",
	"Burrito de Pollo",
	"Nachos con Queso",
	"Alitas de Pollo",
	"Pechuga de Pollo 500g",
	"Pierna de Pollo 500g",
	"Carne de Res 500g",
	"Carne de Cerdo 500g",
	"Chuleta de Cerdo 500g",
	"Costillas de Cerdo 500g",
	"Salchichas x6",
	"Jamón 250g",
	"Tocino 250g",
	"Salmón Fresco 300g",
	"Atún enlatado",
	"Sardinas enlatadas",
	"Langostinos 300g",
	"Arroz Blanco 1kg",
	"Arroz Integral 1kg",
	"Pasta Spaghetti 500g",
	"Pasta Penne 500g",
	"Frijoles Rojos 500g",
	"Lentejas 500g",
	"Garbanzos 500g",
	"Aceite de Oliva 500ml",
	"Aceite Vegetal 1L",
	"Vinagre Balsámico 250ml",
	"Salsa de Tomate 500g",
	"Salsa BBQ 250ml",
	"Salsa de Soya 250ml",
	"Mayonesa 500g",
	"Ketchup 500g",
	"Mostaza 250g",
	"Sal Marina 500g",
	"Pimienta Negra 50g",
	"Orégano 20g",
	"Comino 20g",
	"Canela 20g",
	"Ajo en Polvo 50g",
	"Paprika 50g",
	"Harina de Trigo 1kg",
	"Harina de Almendras 500g",
	"Azúcar Blanca 1kg",
	"Azúcar Morena 500g",
	"Miel de Abeja 500g",
	"Mermelada de Fresa 250g",
	"Mermelada de Durazno 250g",
	"Café Molido 250g",
	"Café Instantáneo 100g",
	"Té Negro x20",
	"Té Verde x20",
	"Té de Manzanilla x20",
	"Cerveza Lager 330ml",
	"Cerveza IPA 330ml",
	"Cerveza Artesanal 500ml",
	"Vino Tinto 750ml",
	"Vino Blanco 750ml",
	"Whisky 750ml",
	"Ron Añejo 750ml",
	"Vodka 750ml",
	"Tequila 750ml",
	"Gin Tonic 750ml",
	"Jabón de Baño",
	"Shampoo",
	"Acondicionador",
	"Pasta Dental",
	"Crema Dental",
	"Desodorante",
	"Jabón Líquido 500ml",
	"Detergente en Polvo 1kg",
	"Suavizante 1L",
	"Limpiavidrios 500ml",
	"Desinfectante 1L",
	"Papel Higiénico x4",
	"Servilletas x100",
	"Toallas de Papel x2",
	"Pañales Talla M x20",
	"Pañales Talla L x20",
	"Leche en Polvo 400g",
	"Fórmula Infantil 400g",
	"Vitaminas x30",
	"Analgésicos x10",
	"Antigripal x10",
	"Jarabe para la Tos",
	"Alcohol en Gel 250ml",
	"Mascarillas x50",
	"Batería AA x4",
	"Batería AAA x4",
	"Pilas Recargables",
	"Cable USB",
	"Cargador de Celular",
	"Auriculares",
	"Mouse Inalámbrico",
	"Teclado USB",
	"Pendrive 32GB",
	"Pendrive 64GB",
	"Cuaderno 100 hojas",
	"Lápiz HB",
	"Bolígrafo Azul",
	"Marcadores x4",
	"Cinta Adhesiva",
	"Tijeras",
	"Grapadora",
	"Grapas x100",
	"Regla 30cm",
	"Pegamento en Barra",
	"Pintura Acrílica",
	"Pincel Set x3",
	"Lienzo 20x30cm",
	"Cuerda 10m",
	"Martillo",
	"Destornillador",
	"Alicate",
	"Clavos x50",
	"Tornillos x50",
	"Cinta Aislante",
	"Lámpara LED",
	"Bombillo LED",
	"Extensión Eléctrica 3m",
	"Guantes de Jardín",
	"Pala de Jardín",
	"Maceta Mediana",
	"Tierra para Macetas 5kg",
	"Semillas de Tomate",
	"Semillas de Lechuga",
	"Semillas de Albahaca",
	"Fertilizante 1kg",
	"Manguera 10m",
	"Rastrillo",
	"Podadora",
	"Mascota Alimento 1kg",
	"Mascota Alimento 5kg",
	"Collar para Perro",
	"Correa para Perro",
	"Juguete para Perro",
	"Juguete para Gato",
	"Arena para Gato 5kg",
	"Shampoo para Mascotas",
	"Pelota de Fútbol",
	"Pelota de Baloncesto",
	"Raqueta de Tenis",
	"Pelotas de Tenis x3",
	"Pesas 2kg",
	"Cuerda para Saltar",
	"Mat de Yoga",
	"Botella Deportiva 750ml",
	"Mochila Deportiva",
	"Zapatos Running Talla 42",
	"Zapatos Running Talla 43",
	"Camiseta Deportiva M",
	"Camiseta Deportiva L",
	"Shorts Deportivos M",
	"Shorts Deportivos L",
	"Gorra Deportiva",
	"Gafas de Sol",
	"Reloj Deportivo",
	"Pulsera Fitness",
	"Bicicleta Urbana",
	"Casco de Bicicleta",
	"Guantes de Ciclismo",
	"Candado para Bicicleta",
	"Inflador de Bicicleta",
	"Kit de Reparación",
	"Linterna LED",
	"Navaja Multiusos",
	"Brújula",
	"Mapa Local",
	"Botiquín de Primeros Auxilios",
	"Silla de Camping",
	"Carpa 2 Personas",
	"Saco de Dormir",
	"Hervidor de Camping",
	"Plato Camping",
	"Vaso Camping",
	"Cubiertos Camping",
	"Bolsa Térmica",
	"Hielo Gel x2",
	"Conservadora 20L",
	"Silla de Playa",
	"Sombrilla de Playa",
	"Toalla de Playa",
	"Protector Solar SPF 50",
	"Protector Solar SPF 30",
	"Repelente de Insectos",
	"After Sun",
	"Gafas de Natación",
	"Tapones de Oídos",
	"Gorro de Natación",
	"Aletas de Natación",
	"Flotador Infantil",
	"Salvavidas",
	"Tabla de Surf",
	"Bodyboard",
	"Neopreno Talla M",
	"Neopreno Talla L",
	"Aceite para Motos 1L",
	"Líquido de Frenos",
	"Anticongelante 1L",
	"Limpiaparabrisas 1L",
	"Esponja para Auto",
	"Cera para Auto",
	"Ambientador para Auto",
	"Fundas para Asientos",
	"Alfombras para Auto",
	"Organizador para Auto",
	"Cargador de Auto USB",
	"Soporte para Celular Auto",
	"GPS para Auto",
	"Cámara de Retroceso",
	"Alarma para Auto",
	"Candado para Moto",
	"Cadena para Moto",
	"Casco para Moto",
	"Guantes para Moto",
	"Chaqueta para Moto M",
	"Chaqueta para Moto L",
	"Botas para Moto Talla 42",
	"Botas para Moto Talla 43",
	"Impermeable para Moto",
	"Maletas para Moto",
	"Top Box para Moto",
	"Intercomunicador para Moto",
	"Guantes Tácticos",
	"Linterna Táctica",
	"Cuchillo Táctico",
	"Mochila Táctica 30L",
	"Mochila Táctica 50L",
	"Botas Tácticas Talla 42",
	"Botas Tácticas Talla 43",
	"Pantalón Táctico M",
	"Pantalón Táctico L",
	"Camisa Táctica M",
	"Camisa Táctica L",
	"Chaleco Táctico",
	"Casco Táctico",
	"Gafas Tácticas",
	"Máscara Táctica",
	"Rodilleras Tácticas",
	"Coderas Tácticas",
	"Cinturón Táctico",
	"Cantimplora 1L",
	"Brújula Militar",
	"Mapa Topográfico",
	"Kit de Supervivencia",
	"Manta Térmica",
	"Sábana Ajustable Individual",
	"Sábana Ajustable Doble",
	"Fundas de Almohada x2",
	"Edredón Individual",
	"Edredón Doble",
	"Cortina para Baño",
	"Toalla de Baño",
	"Toalla de Manos",
	"Toalla de Pies",
	"Alfombra de Baño",
	"Dispensador de Jabón",
	"Portacepillos",
	"Espejo para Baño",
	"Organizador de Baño",
	"Cesto de Ropa",
	"Plancha de Ropa",
	"Tabla de Planchar",
	"Perchas x10",
	"Perchas x20",
	"Organizador de Zapatos",
	"Organizador de Ropa",
	"Caja de Almacenamiento",
	"Caja de Almacenamiento con Tapa",
	"Estante Modular",
	"Cajonera Plástica",
	"Cajonera de Madera",
	"Mesa Plegable",
	"Silla Plegable",
	"Silla de Escritorio",
	"Escritorio de Madera",
	"Lámpara de Escritorio",
	"Organizador de Escritorio",
	"Portalápices",
	"Calendario de Escritorio",
	"Pizarra Blanca",
	"Pizarra Magnética",
	"Notas Adhesivas x100",
	"Marcador para Pizarra x4",
	"Borrador para Pizarra",
	"Engrapadora Eléctrica",
	"Perforadora",
	"Corrector Líquido",
	"Resaltadores x6",
	"Post-it x100",
	"Sobre Manila x50",
	"Sobre Blanco x50",
	"Etiquetas Adhesivas x100",
	"Cinta Correctora",
	"Cinta de Embalar",
	"Caja de Cartón Mediana",
	"Caja de Cartón Grande",
	"Burrito Vegetariano",
	"Taco Vegetariano",
	"Ensalada César",
	"Ensalada Griega",
	"Ensalada de Quinoa",
	"Sopa de Pollo",
	"Sopa de Tomate",
	"Sopa de Lentejas",
	"Sopa de Verduras",
	"Caldo de Res",
	"Caldo de Pollo",
	"Arroz con Pollo",
	"Arroz con Camarones",
	"Paella",
	"Risotto de Champiñones",
	"Risotto de Mariscos",
	"Pollo a la Plancha",
	"Pollo Frito",
	"Pollo al Horno",
	"Pechuga a la Plancha",
	"Pechuga Empanizada",
	"Muslo de Pollo",
	"Ala de Pollo",
	"Filete de Res",
	"Churrasco",
	"Bife de Chorizo",
	"T-Bone",
	"Costillas BBQ",
	"Lomo de Cerdo",
	"Lomo de Res",
	"Milanesa de Pollo",
	"Milanesa de Res",
	"Milanesa de Cerdo",
	"Filete de Pescado",
	"Ceviche",
	"Pescado Frito",
	"Camarones al Ajillo",
	"Camarones Empanizados",
	"Langosta",
	"Pulpo a la Gallega",
	"Calamares Fritos",
	"Paella Valenciana",
	"Paella de Mariscos",
	"Fideuá",
	"Gazpacho",
	"Salmorejo",
	"Tortilla Española",
	"Croquetas de Jamón",
	"Croquetas de Pollo",
	"Patatas Bravas",
	"Pan con Tomate",
	"Jamón Ibérico",
	"Chorizo Ibérico",
	"Queso Manchego",
	"Pan de Cristal",
	"Rosquillas",
	"Churros",
	"Porras",
	"Natillas",
	"Arroz con Leche",
	"Tarta de Santiago",
	"Tarta de Queso",
	"Flan",
	"Crema Catalana",
	"Carajillo",
	"Café Solo",
	"Café Cortado",
	"Café Bombón",
	"Café Americano",
	"Café con Hielo",
	"Chocolate Caliente",
	"Té con Leche",
	"Té con Limón",
	"Té con Miel",
	"Cola Cao",
	"Agua de Valencia",
	"Sangría",
	"Tinto de Verano",
	"Clara",
	"Caña",
	"Doble",
	"Tercio",
	"Quinto",
	"Jarra",
	"Litrona",
	"Copa de Vino",
	"Copa de Cava",
	"Chupito",
	"Cubata",
	"Mojito",
	"Caipiriña",
	"Margarita",
	"Daiquirí",
	"Piña Colada",
	"San Francisco",
	"Gin Tonic",
	"Vermut",
	"Licor 43",
	"Pacharán",
	"Orujo",
	"Cocido Madrileño",
	"Callos a la Madrileña",
	"Bocata de Calamares",
	"Bravas",
	"Tortilla de Patatas",
	"Gambas al Ajillo",
	"Boquerones en Vinagre",
	"Ensaladilla Rusa",
	"Pimientos de Padrón",
	"Chipirones",
	"Zarajos",
	"Huevos Rotos",
	"Pincho de Tortilla",
	"Pincho de Morcilla",
	"Pincho de Jamón",
	"Txistorra",
	"Pintxo de Bonito",
	"Pintxo de Gilda",
	"Tarta de Queso Vasca",
	"Marmitako",
	"Bacalao al Pil Pil",
	"Chipirones en su Tinta",
	"Kokotxas",
	"Txuleta",
	"Idiazábal",
	"Txakoli",
	"Sidra Natural",
	"Queso Cabrales",
	"Sidra El Gaitero",
	"Fabada Asturiana",
	"Cachopo",
	"Yogurt Griego Natural",
	"Yogurt Griego con Miel",
	"Yogurt Griego con Nueces",
	"Yogurt Griego con Frutas",
	"Yogurt Griego con Granola",
	"Yogurt Kéfir Natural",
	"Yogurt Kéfir con Frutas",
	"Yogurt Kéfir con Semillas",
	"Yogurt Bebible Natural",
	"Yogurt Bebible de Fresa",
	"Yogurt Bebible de Plátano",
	"Yogurt Bebible de Chocolate",
	"Yogurt Bebible de Vainilla",
	"Yogurt Bebible de Café",
	"Yogurt Bebible de Caramelo",
	"Yogurt Bebible de Maracuyá",
	"Yogurt Bebible de Guanábana",
	"Yogurt Bebible de Mora",
	"Yogurt Bebible de Lulo",
	"Yogurt Bebible de Curuba",
	"Yogurt sin Lactosa Natural",
	"Yogurt sin Lactosa de Fresa",
	"Yogurt sin Lactosa de Durazno",
	"Yogurt sin Lactosa de Arándanos",
	"Yogurt sin Lactosa de Maracuyá",
	"Yogurt sin Lactosa de Kiwi",
	"Yogurt sin Lactosa de Pera",
	"Yogurt sin Lactosa de Manzana",
	"Yogurt sin Lactosa de Mango",
	"Yogurt sin Lactosa de Piña",
	"Yogurt sin Lactosa de Coco",
	"Yogurt sin Lactosa de Almendra",
	"Yogurt sin Lactosa de Avellana",
	"Yogurt sin Lactosa de Nuez",
	"Yogurt sin Lactosa de Macadamia",
	"Yogurt sin Lactosa de Pistacho",
	"Yogurt sin Lactosa de Castaña",
	"Yogurt Islandés Skyr Natural",
	"Yogurt Islandés Skyr con Frutas",
	"Yogurt Islandés Skyr con Miel",
	"Yogurt Islandés Skyr con Nueces",
	"Yogurt Kéfir sin Lactosa",
	"Leche de Almendras",
	"Leche de Soja",
	"Leche de Avena",
	"Leche de Coco",
	"Leche Deslactosada",
	"Leche Semidescremada",
	"Leche Entera",
	"Leche en Polvo",
	"Mantequilla sin Sal",
	"Mantequilla con Sal",
	"Margarina",
	"Aceite de Coco",
	"Aceite de Girasol",
	"Aceite de Canola",
	"Aceite de Sésamo",
	"Aceite de Aguacate",
	"Vinagre de Manzana",
	"Vinagre de Vino",
	"Vinagre de Arroz",
	"Mostaza Dijon",
	"Mostaza Americana",
	"Salsa de Chile",
	"Salsa Tártara",
	"Salsa César",
	"Salsa Ranch",
	"Salsa de Queso",
	"Salsa de Piña",
	"Salsa de Mango",
	"Salsa de Tamarindo",
	"Salsa de Cacahuate",
	"Salsa de Soja Baja en Sodio",
	"Salsa Teriyaki",
	"Salsa Hoisin",
	"Salsa de Ostras",
	"Salsa Sriracha",
	"Salsa Tabasco",
	"Salsa Cholula",
	"Salsa Valentina",
	"Aderezo Italiano",
	"Aderezo de Ajo",
	"Aderezo de Mostaza y Miel",
	"Aderezo de Frambuesa",
	"Aderezo de Blue Cheese",
	"Aderezo de Mil Islas",
	"Aderezo de Vinagreta",
	"Aderezo de Limón",
	"Aderezo de Aguacate",
	"Aderezo de Yogurt",
	"Mayonesa Light",
	"Mayonesa con Ajo",
	"Mayonesa de Aguacate",
	"Ketchup Orgánico",
	"Ketchup Picante",
	"Ketchup sin Azúcar",
	"Mostaza con Miel",
	"Mostaza Picante",
	"Mostaza de Granos",
	"Relish de Pepinillos",
	"Cebollas Encurtidas",
	"Aceitunas Verdes",
	"Aceitunas Negras",
	"Aceitunas Rellenas",
	"Alcaparras",
	"Pepinillos",
	"Jalapeños enlatados",
	"Chiles en Vinagre",
	"Ají Amarillo",
	"Ají Panca",
	"Rocoto",
	"Habanero",
	"Chipotle",
	"Guajillo",
	"Pasilla",
	"Ancho",
	"Cayena",
	"Paprika Ahumada",
	"Pimentón Dulce",
	"Pimentón Picante",
	"Curry en Polvo",
	"Curry Rojo",
	"Curry Verde",
	"Curry Amarillo",
	"Masala",
	"Garam Masala",
	"Tandoori Masala",
	"Ras el Hanout",
	"Za'atar",
	"Sumac",
	"Harissa",
	"Berbere",
	"Dukkah",
	"Shichimi Togarashi",
	"Jengibre en Polvo",
	"Cúrcuma",
	"Cardamomo",
	"Clavo de Olor",
	"Nuez Moscada",
	"Anís Estrellado",
	"Semillas de Hinojo",
	"Semillas de Comino",
	"Semillas de Mostaza",
	"Semillas de Amapola",
	"Semillas de Sésamo",
	"Semillas de Chía",
	"Semillas de Lino",
	"Semillas de Calabaza",
	"Semillas de Girasol",
	"Polen de Abeja",
	"Jalea Real",
	"Propóleo",
	"Cera de Abeja",
	"Miel de Manuka",
	"Miel de Castaño",
	"Miel de Romero",
	"Miel de Lavanda",
	"Miel de Eucalipto",
	"Miel de Azahar",
	"Miel de Brezo",
	"Miel de Mil Flores",
	"Miel de Agave",
	"Jarabe de Arce",
	"Jarabe de Agave",
	"Stevia",
	"Eritritol",
	"Xilitol",
	"Maltitol",
	"Sorbitol",
	"Sucralosa",
	"Azúcar de Coco",
	"Azúcar de Dátil",
	"Azúcar de Caña",
	"Panela",
	"Rapadura",
	"Piloncillo",
	"Chancaca",
	"Miel de Caña",
	"Miel de Palma",
	"Miel de Maíz",
	"Miel de Arroz",
	"Dextrosa",
	"Glucosa",
	"Fructosa",
	"Maltodextrina",
	"Inulina",
	"Fibra de Acacia",
	"Fibra de Trigo",
	"Fibra de Avena",
	"Psyllium",
	"Goma Xantana",
	"Goma Guar",
	"Carragenina",
	"Agar Agar",
	"Pectina",
	"Almidón de Maíz",
	"Almidón de Tapioca",
	"Almidón de Patata",
	"Harina de Arroz",
	"Harina de Maíz",
	"Harina de Avena",
	"Harina de Centeno",
	"Harina de Espelta",
	"Harina de Kamut",
	"Harina de Trigo Sarraceno",
	"Harina de Garbanzo",
	"Harina de Lenteja",
	"Harina de Quinoa",
	"Harina de Amaranto",
	"Harina de Teff",
	"Harina de Sorgho",
	"Harina de Mijo",
	"Harina de Yuca",
	"Harina de Plátano",
	"Harina de Coco",
	"Harina de Almendra",
	"Harina de Castaña",
	"Harina de Avellana",
	"Harina de Pistacho",
	"Harina de Nuez",
	"Harina de Macadamia",
	"Harina de Quinoa Orgánica",
	"Harina de Arroz Integral",
	"Harina de Avena sin Gluten",
	"Premezcla para Pan",
	"Premezcla para Pizza",
	"Premezcla para Tortas",
	"Premezcla para Brownies",
	"Premezcla para Galletas",
	"Premezcla para Muffins",
	"Premezcla para Waffles",
	"Premezcla para Pancakes",
	"Premezcla para Crepes",
	"Levadura Fresca",
	"Levadura Seca",
	"Levadura Instantánea",
	"Polvo de Hornear",
	"Bicarbonato de Sodio",
	"Cremor Tártaro",
	"Esencia de Vainilla",
	"Esencia de Almendra",
	"Esencia de Naranja",
	"Esencia de Limón",
	"Esencia de Coco",
	"Esencia de Café",
	"Colorante Rojo",
	"Colorante Azul",
	"Colorante Verde",
	"Colorante Amarillo",
	"Colorante Naranja",
	"Colorante Rosa",
	"Colorante Morado",
	"Colorante Negro",
	"Colorante Blanco",
	"Dorado en Polvo",
	"Plateado en Polvo",
	"Perlas de Azúcar",
	"Fondant Blanco",
	"Fondant de Color",
	"Pasta de Goma",
	"Chocolate de Cobertura",
	"Chocolate Negro 70%",
	"Chocolate Negro 85%",
	"Chocolate Negro 90%",
	"Chocolate con Leche 35%",
	"Chocolate Blanco 28%",
	"Cacao en Polvo",
	"Cacao en Polvo sin Azúcar",
	"Manteca de Cacao",
	"Nibs de Cacao",
	"Massa de Cacao",
	"Pasta de Cacao",
	"Mantequilla de Maní",
	"Mantequilla de Almendra",
	"Mantequilla de Avellana",
	"Mantequilla de Nuez",
	"Mantequilla de Semilla",
	"Mantequilla de Coco",
	"Mantequilla de Girasol",
	"Gelatina sin Sabor",
	"Gelatina de Fresa",
	"Gelatina de Limón",
	"Gelatina de Naranja",
	"Gelatina de Uva",
	"Gelatina de Frambuesa",
	"Gelatina de Cereza",
	"Gelatina de Piña",
	"Gelatina de Manzana",
	"Gelatina de Mango",
	"Gelatina de Melocotón",
	"Gelatina de Frutas Tropicales",
	"Gelatina de Cola",
	"Gelatina de Tamarindo",
	"Flan en Polvo",
	"Natillas en Polvo",
	"Crema Pastelera",
	"Crema Chantilly",
	"Nata para Montar",
	"Nata para Cocinar",
	"Queso Crema",
	"Queso Ricotta",
	"Queso Cottage",
	"Queso Feta",
	"Queso Halloumi",
	"Queso Provolone",
	"Queso Gouda",
	"Queso Edam",
	"Queso Havarti",
	"Queso Brie",
	"Queso Camembert",
	"Queso Roquefort",
	"Queso Gorgonzola",
	"Queso Stilton",
	"Queso Danablu",
	"Queso Bleu d'Auvergne",
	"Queso Cabrales",
	"Queso Picón",
	"Queso Casín",
	"Queso Tetilla",
	"Queso San Simón",
	"Queso Arzúa",
	"Queso Ulloa",
	"Queso Cebreiro",
	"Queso Roncal",
	"Queso Idiazábal",
	"Queso Ossau-Iraty",
	"Queso Mimolette",
	"Queso Comté",
	"Queso Beaufort",
	"Queso Reblochon",
	"Queso Tomme",
	"Queso Raclette",
	"Queso Gruyère",
	"Queso Emmental",
	"Queso Appenzeller",
	"Queso Sbrinz",
	"Queso Tête de Moine",
	"Queso Vacherin",
	"Queso Morbier",
	"Queso Cantal",
	"Queso Laguiole",
	"Queso Salers",
	"Queso Saint-Nectaire",
	"Queso Fourme d'Ambert",
	"Queso Bleu des Causses",
	"Queso Bleu du Vercors",
	"Queso Persillé de Tignes",
	"Queso Abondance",
	"Queso Mont d'Or",
	"Queso Époisses",
	"Queso Munster",
	"Queso Maroilles",
	"Queso Livarot",
	"Queso Pont-l'Évêque",
	"Queso Neufchâtel",
	"Queso Boursin",
	"Queso Port Salut",
	"Queso Saint-Paulin",
	"Queso Chaumes",
	"Queso Saint-André",
	"Queso Explorateur",
	"Queso Pave d'Affinois",
	"Queso Caprice des Dieux",
	"Queso Delice de Bourgogne",
	"Queso Brillat-Savarin",
	"Queso Pierre-Robert",
	"Queso Crottin de Chavignol",
	"Queso Valençay",
	"Queso Selles-sur-Cher",
	"Queso Sainte-Maure",
	"Queso Pouligny-Saint-Pierre",
	"Queso Picodon",
	"Queso Banon",
	"Queso Brocciu",
	"Queso Calenzana",
	"Queso Niolo",
	"Queso Sartori",
	"Queso Piave",
	"Queso Asiago",
	"Queso Montasio",
	"Queso Grana Padano",
	"Queso Parmigiano Reggiano",
	"Queso Pecorino Romano",
	"Queso Pecorino Sardo",
	"Queso Pecorino Toscano",
	"Queso Fiore Sardo",
	"Queso Caciocavallo",
	"Queso Provolone Piccante",
	"Queso Scamorza",
	"Queso Burrata",
	"Queso Stracciatella",
	"Queso Mascarpone",
	"Queso Robiola",
	"Queso Taleggio",
	"Queso Quartirolo",
	"Queso Gorgonzola Dulce",
	"Queso Gorgonzola Piccante",
	"Queso Castelmagno",
	"Queso Bra",
	"Queso Raschera",
	"Queso Toma",
	"Queso Testun",
	"Queso Bettelmatt",
	"Queso Seras",
	"Queso Flor de Guía",
	"Queso Majorero Curado",
	"Queso Palmero Fresco",
	"Queso Palmero Ahumado",
	"Queso de Flor",
	"Queso de Cabra Transhumante",
	"Queso de Cabra Pastoreo",
	"Queso de Oveja Manchego Curado",
	"Queso de Oveja Manchego Semi",
	"Queso de Oveja Idiazábal Ahumado",
	"Queso de Oveja Roncal",
	"Queso de Vaca San Simón",
	"Queso de Vaca Tetilla",
	"Queso Mezcla Castellano",
	"Queso Mezcla Zamorano",
	"Queso Mezcla Torta del Casar",
	"Queso Mezcla La Serena",
	"Queso Mezcla Los Ibores",
	"Queso Fresco Burgos",
	"Queso Fresco Gallego",
	"Queso Fresco Asturiano",
	"Queso Fresco Cantábrico",
	"Queso Fresco del País Vasco",
	"Yogurt Natural sin Azúcar",
	"Yogurt Natural con Azúcar",
	"Yogurt con Muesli",
	"Yogurt con Frutos Secos",
	"Yogurt con Semillas",
	"Yogurt con Proteína",
	"Yogurt con Colágeno",
	"Yogurt con Magnesio",
	"Yogurt con Calcio",
	"Yogurt con Vitamina D",
	"Yogurt con Probióticos",
	"Yogurt con Lactobacillus",
	"Yogurt con Bifidobacterium",
	"Yogurt con Fibra",
	"Yogurt con Omega-3",
	"Yogurt para Niños",
	"Yogurt para Adultos Mayores",
	"Yogurt para Deportistas",
	"Yogurt para Diabéticos",
	"Yogurt sin Lactosa Natural",
	"Yogurt sin Lactosa de Fresa",
	"Yogurt sin Lactosa de Durazno",
	"Yogurt sin Lactosa de Arándanos",
	"Yogurt sin Lactosa de Maracuyá",
	"Yogurt sin Lactosa de Kiwi",
	"Yogurt sin Lactosa de Pera",
	"Yogurt sin Lactosa de Manzana",
	"Yogurt sin Lactosa de Mango",
	"Yogurt sin Lactosa de Piña",
	"Yogurt sin Lactosa de Coco",
	"Yogurt sin Lactosa de Almendra",
	"Yogurt sin Lactosa de Avellana",
	"Yogurt sin Lactosa de Nuez",
	"Yogurt sin Lactosa de Macadamia",
	"Yogurt sin Lactosa de Pistacho",
	"Yogurt sin Lactosa de Castaña",
	"Yogurt Griego con Chía",
	"Yogurt Griego con Lino",
	"Yogurt Griego con Hemp",
	"Yogurt Griego con Proteína",
	"Yogurt Griego sin Lactosa",
	"Yogurt Islandés Skyr con Granola",
	"Yogurt Islandés Skyr con Semillas",
	"Yogurt Islandés Skyr sin Lactosa",
	"Yogurt Kéfir con Miel",
	"Yogurt Kéfir sin Lactosa",
	"Yogurt Bebible de Cookies & Cream",
	"Yogurt Bebible de Brownie",
	"Yogurt Bebible de Cheesecake",
	"Yogurt Bebible de Tiramisú",
	"Yogurt Bebible de Pistacho",
	"Yogurt Bebible de Guanábana",
	"Yogurt Bebible de Feijoa",
	"Yogurt Bebible de Borojó",
	"Yogurt Bebible de Arazá",
	"Yogurt Bebible de Copoazú",
	"Yogurt Bebible de Aguaje",
	"Yogurt Bebible de Camu Camu",
	"Yogurt Bebible de Sacha Inchi",
	"Yogurt Bebible de Maca",
	"Yogurt Bebible de Cat's Claw",
	"Yogurt Bebible de Huanarpo",
	"Yogurt Bebible de Chuchuhuasi",
	"Yogurt Bebible de Uña de Gato",
	"Yogurt Bebible de Sangre de Grado",
	"Yogurt Bebible de Copaiba",
	"Yogurt Bebible de Andiroba",
	"Yogurt Bebible de Buriti",
	"Yogurt Bebible de Murumuru",
	"Yogurt Bebible de Tucumã",
	"Yogurt Bebible de Bacuri",
	"Yogurt Bebible de Ucuuba",
	"Yogurt Bebible de Ojon",
	"Yogurt Bebible de Brazil Nut",
	"Yogurt Bebible de Cupuaçu",
	"Yogurt Bebible de Açai",
	"Yogurt Bebible de Guaraná",
	"Yogurt Bebible de Yerba Mate",
	"Yogurt Bebible de Stevia",
	"Yogurt Bebible de Monk Fruit",
];

async function main() {
	const args = process.argv.slice(2);
	const orgIdArg = args.find((a) => a.startsWith("--org-id="))?.split("=")[1];
	const forceArg = args.includes("--force");

	let selectedOrg: { id: string; name: string; slug: string } | undefined;

	if (orgIdArg) {
		const org = await db
			.select()
			.from(organization)
			.where(eq(organization.id, orgIdArg))
			.get();
		if (!org) {
			console.error(`[ERROR] Organization with id "${orgIdArg}" not found.`);
			process.exit(1);
		}
		selectedOrg = org;
		console.log(`[INFO] Using organization from --org-id flag: ${selectedOrg.name}`);
	} else {
		console.log("[INFO] Fetching organizations...\n");

		const orgs = await db.select().from(organization);
		if (orgs.length === 0) {
			console.error("[ERROR] No organizations found in the database.");
			process.exit(1);
		}

		console.log("Available organizations:");
		orgs.forEach((org, idx) => {
			console.log(
				`  ${idx + 1}. ${org.name} (slug: ${org.slug}, id: ${org.id})`,
			);
		});

		const answer = await rl.question("\nSelect organization (number): ");
		const selectedIndex = parseInt(answer.trim(), 10) - 1;
		selectedOrg = orgs[selectedIndex];

		if (!selectedOrg) {
			console.error("[ERROR] Invalid selection.");
			process.exit(1);
		}
	}

	console.log(
		`\n[INFO] Selected organization: ${selectedOrg.name} (${selectedOrg.id})`,
	);

	// Check existing data
	const existingCategories = await db
		.select({ count: sql<number>`count(*)` })
		.from(category)
		.where(eq(category.organizationId, selectedOrg.id));

	const existingProducts = await db
		.select({ count: sql<number>`count(*)` })
		.from(product)
		.where(eq(product.organizationId, selectedOrg.id));

	const catCount = existingCategories[0].count;
	const prodCount = existingProducts[0].count;

	if (catCount > 0 || prodCount > 0) {
		console.log(
			`\n[WARNING] This organization already has ${catCount} categories and ${prodCount} products.`,
		);
		if (forceArg) {
			console.log("[INFO] --force flag set, continuing...");
		} else {
			const confirm = await rl.question(
				"Do you want to continue seeding? (yes/no): ",
			);
			if (confirm.trim().toLowerCase() !== "yes") {
				console.log("[INFO] Aborted.");
				process.exit(0);
			}
		}
	}

	// Seed 100 categories
	console.log("[INFO] Seeding 100 categories...");
	await seed(db, { category }).refine((f) => ({
		category: {
			count: 100,
			columns: {
				id: f.uuid(),
				organizationId: f.default({ defaultValue: selectedOrg.id }),
				name: f.valuesFromArray({
					values: CATEGORY_NAMES,
					isUnique: false,
				}),
				description: f.loremIpsum({ sentencesCount: 2 }),
				createdAt: f.default({ defaultValue: new Date() }),
			},
		},
	}));

	// Fetch created category IDs
	const categories = await db
		.select({ id: category.id })
		.from(category)
		.where(eq(category.organizationId, selectedOrg.id));

	const categoryIds = categories.map((c) => c.id);
	if (categoryIds.length === 0) {
		console.error("[ERROR] No categories were created.");
		process.exit(1);
	}

	console.log(`[INFO] Created ${categoryIds.length} categories.`);

	// Seed 1000 products
	console.log("[INFO] Seeding 1000 products...");
	await seed(db, { product }).refine((f) => ({
		product: {
			count: 1000,
			columns: {
				id: f.uuid(),
				organizationId: f.default({ defaultValue: selectedOrg.id }),
				categoryId: f.valuesFromArray({ values: categoryIds }),
				name: f.valuesFromArray({ values: PRODUCT_NAMES }),
				sku: f.default({ defaultValue: null }),
				barcode: f.default({ defaultValue: null }),
				price: f.int({ minValue: 5000, maxValue: 500000 }),
				cost: f.int({ minValue: 1000, maxValue: 300000 }),
				taxRate: f.valuesFromArray({ values: [0, 5, 19] }),
				isModifier: f.default({ defaultValue: false }),
				trackInventory: f.default({ defaultValue: true }),
				stock: f.int({ minValue: 0, maxValue: 500 }),
				isFavorite: f.boolean(),
				deletedAt: f.default({ defaultValue: null }),
				createdAt: f.default({ defaultValue: new Date() }),
			},
		},
	}));

	const finalProducts = await db
		.select({ count: sql<number>`count(*)` })
		.from(product)
		.where(eq(product.organizationId, selectedOrg.id));

	console.log(
		`[SUCCESS] Organization now has ${finalProducts[0].count} products total.`,
	);
	console.log("[SUCCESS] Done!");
}

main()
	.then(() => rl.close())
	.catch((err) => {
		console.error(err);
		rl.close();
		process.exit(1);
	});
