// @generated drizzle-zero signature:sha256:2627d0aabcd7c3236c3726d84667b3e6388a0bad83fc07d418ffa0cf48f5ec6f
// This file was automatically generated by drizzle-zero.
// You should NOT make any changes in this file as it will be overwritten.

import type { Row } from "@rocicorp/zero";
import { createBuilder } from "@rocicorp/zero";

const cashMovementTable = {
  name: "cashMovement",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    organizationId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "organization_id",
    },
    shiftId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "shift_id",
    },
    type: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    paymentMethod: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "payment_method",
    },
    amount: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
    description: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
  },
  primaryKey: ["id"],
  serverName: "cash_movement",
} as const;
const categoryTable = {
  name: "category",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    organizationId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "organization_id",
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    description: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
  },
  primaryKey: ["id"],
} as const;
const creditAccountTable = {
  name: "creditAccount",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    organizationId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "organization_id",
    },
    customerId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "customer_id",
    },
    balance: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    interestRate: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "interest_rate",
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
  serverName: "credit_account",
} as const;
const creditTransactionTable = {
  name: "creditTransaction",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    organizationId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "organization_id",
    },
    creditAccountId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "credit_account_id",
    },
    saleId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "sale_id",
    },
    paymentId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "payment_id",
    },
    type: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    amount: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
    notes: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
  },
  primaryKey: ["id"],
  serverName: "credit_transaction",
} as const;
const customerTable = {
  name: "customer",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    organizationId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "organization_id",
    },
    type: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    documentType: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "document_type",
    },
    documentNumber: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "document_number",
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    email: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    phone: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    address: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    city: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    taxRegime: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "tax_regime",
    },
    deletedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "deleted_at",
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
} as const;
const inventoryMovementTable = {
  name: "inventoryMovement",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    organizationId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "organization_id",
    },
    productId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "product_id",
    },
    userId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "user_id",
    },
    type: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    quantity: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
    notes: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
  },
  primaryKey: ["id"],
  serverName: "inventory_movement",
} as const;
const invitationTable = {
  name: "invitation",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    organizationId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "organization_id",
    },
    email: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    role: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    status: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    expiresAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "expires_at",
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    inviterId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "inviter_id",
    },
  },
  primaryKey: ["id"],
} as const;
const memberTable = {
  name: "member",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    organizationId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "organization_id",
    },
    userId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "user_id",
    },
    role: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
  },
  primaryKey: ["id"],
} as const;
const organizationTable = {
  name: "organization",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    slug: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    logo: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    metadata: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
  },
  primaryKey: ["id"],
} as const;
const organizationJoinLinkTable = {
  name: "organizationJoinLink",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    organizationId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "organization_id",
    },
    token: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    role: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    label: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    createdByUserId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "created_by_user_id",
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    expiresAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "expires_at",
    },
    maxUses: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "max_uses",
    },
    useCount: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "use_count",
    },
    lastUsedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "last_used_at",
    },
    lastUsedByUserId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "last_used_by_user_id",
    },
    revokedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "revoked_at",
    },
  },
  primaryKey: ["id"],
  serverName: "organization_join_link",
} as const;
const organizationModuleEntitlementTable = {
  name: "organizationModuleEntitlement",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    organizationId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "organization_id",
    },
    moduleKey: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "module_key",
    },
    status: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    updatedByUserId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "updated_by_user_id",
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
  serverName: "organization_module_entitlement",
} as const;
const paymentTable = {
  name: "payment",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    organizationId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "organization_id",
    },
    saleId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "sale_id",
    },
    shiftId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "shift_id",
    },
    method: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    reference: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    amount: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
    appliedAmount: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "applied_amount",
    },
    changeAmount: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "change_amount",
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
  },
  primaryKey: ["id"],
} as const;
const pedidoTable = {
  name: "pedido",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    organizationId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "organization_id",
    },
    customerId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "customer_id",
    },
    saleId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "sale_id",
    },
    acceptedByUserId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "accepted_by_user_id",
    },
    orderNumber: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "order_number",
    },
    status: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    fulfillment: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    source: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    contactName: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "contact_name",
    },
    contactPhone: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "contact_phone",
    },
    deliveryAddress: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "delivery_address",
    },
    deliveryNotes: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "delivery_notes",
    },
    notes: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    subtotal: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    taxAmount: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "tax_amount",
    },
    totalAmount: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "total_amount",
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
    closedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "closed_at",
    },
  },
  primaryKey: ["id"],
} as const;
const pedidoItemTable = {
  name: "pedidoItem",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    organizationId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "organization_id",
    },
    orderId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "order_id",
    },
    productId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "product_id",
    },
    quantity: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
    unitPrice: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "unit_price",
    },
    taxRate: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "tax_rate",
    },
    totalAmount: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "total_amount",
    },
    notes: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
  },
  primaryKey: ["id"],
  serverName: "pedido_item",
} as const;
const productTable = {
  name: "product",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    organizationId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "organization_id",
    },
    categoryId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "category_id",
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    sku: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    barcode: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    price: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
    cost: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    taxRate: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "tax_rate",
    },
    isModifier: {
      type: "boolean",
      optional: true,
      customType: null as unknown as boolean,
      serverName: "is_modifier",
    },
    trackInventory: {
      type: "boolean",
      optional: true,
      customType: null as unknown as boolean,
      serverName: "track_inventory",
    },
    stock: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    minStock: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "min_stock",
    },
    reorderQuantity: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "reorder_quantity",
    },
    isFavorite: {
      type: "boolean",
      optional: true,
      customType: null as unknown as boolean,
      serverName: "is_favorite",
    },
    deletedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "deleted_at",
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
  },
  primaryKey: ["id"],
} as const;
const restaurantAreaTable = {
  name: "restaurantArea",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    organizationId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "organization_id",
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    sortOrder: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "sort_order",
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
  serverName: "restaurant_area",
} as const;
const restaurantKitchenTicketTable = {
  name: "restaurantKitchenTicket",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    organizationId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "organization_id",
    },
    orderId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "order_id",
    },
    createdByUserId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "created_by_user_id",
    },
    sequenceNumber: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "sequence_number",
    },
    status: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
    printedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "printed_at",
    },
  },
  primaryKey: ["id"],
  serverName: "restaurant_kitchen_ticket",
} as const;
const restaurantOrderTable = {
  name: "restaurantOrder",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    organizationId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "organization_id",
    },
    tableId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "table_id",
    },
    openedByUserId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "opened_by_user_id",
    },
    closedByUserId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "closed_by_user_id",
    },
    saleId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "sale_id",
    },
    orderNumber: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "order_number",
    },
    status: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    guestCount: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "guest_count",
    },
    notes: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
    closedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "closed_at",
    },
  },
  primaryKey: ["id"],
  serverName: "restaurant_order",
} as const;
const restaurantOrderItemTable = {
  name: "restaurantOrderItem",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    organizationId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "organization_id",
    },
    orderId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "order_id",
    },
    kitchenTicketId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "kitchen_ticket_id",
    },
    productId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "product_id",
    },
    quantity: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
    unitPrice: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "unit_price",
    },
    taxRate: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "tax_rate",
    },
    discountAmount: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "discount_amount",
    },
    notes: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    status: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
    sentAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "sent_at",
    },
    readyAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "ready_at",
    },
    servedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "served_at",
    },
    cancelledAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "cancelled_at",
    },
  },
  primaryKey: ["id"],
  serverName: "restaurant_order_item",
} as const;
const restaurantOrderItemModifierTable = {
  name: "restaurantOrderItemModifier",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    organizationId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "organization_id",
    },
    orderItemId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "order_item_id",
    },
    modifierProductId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "modifier_product_id",
    },
    quantity: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
    unitPrice: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "unit_price",
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
  },
  primaryKey: ["id"],
  serverName: "restaurant_order_item_modifier",
} as const;
const restaurantTable = {
  name: "restaurantTable",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    organizationId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "organization_id",
    },
    areaId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "area_id",
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    seats: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    sortOrder: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "sort_order",
    },
    isActive: {
      type: "boolean",
      optional: true,
      customType: null as unknown as boolean,
      serverName: "is_active",
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
  serverName: "restaurant_table",
} as const;
const saleTable = {
  name: "sale",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    organizationId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "organization_id",
    },
    shiftId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "shift_id",
    },
    customerId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "customer_id",
    },
    userId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "user_id",
    },
    subtotal: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    taxAmount: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "tax_amount",
    },
    discountAmount: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "discount_amount",
    },
    totalAmount: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "total_amount",
    },
    status: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
  },
  primaryKey: ["id"],
} as const;
const saleItemTable = {
  name: "saleItem",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    saleId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "sale_id",
    },
    organizationId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "organization_id",
    },
    productId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "product_id",
    },
    quantity: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
    unitPrice: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "unit_price",
    },
    subtotal: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
    taxRate: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "tax_rate",
    },
    taxAmount: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "tax_amount",
    },
    discountAmount: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "discount_amount",
    },
    totalAmount: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "total_amount",
    },
  },
  primaryKey: ["id"],
  serverName: "sale_item",
} as const;
const saleItemModifierTable = {
  name: "saleItemModifier",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    saleItemId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "sale_item_id",
    },
    organizationId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "organization_id",
    },
    modifierProductId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "modifier_product_id",
    },
    quantity: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
    unitPrice: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "unit_price",
    },
    subtotal: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
  },
  primaryKey: ["id"],
  serverName: "sale_item_modifier",
} as const;
const shiftTable = {
  name: "shift",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    organizationId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "organization_id",
    },
    userId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "user_id",
    },
    terminalId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "terminal_id",
    },
    terminalName: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "terminal_name",
    },
    status: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    startingCash: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "starting_cash",
    },
    openedAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "opened_at",
    },
    closedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "closed_at",
    },
    notes: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
  },
  primaryKey: ["id"],
} as const;
const shiftClosureTable = {
  name: "shiftClosure",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    shiftId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "shift_id",
    },
    paymentMethod: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "payment_method",
    },
    expectedAmount: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "expected_amount",
    },
    actualAmount: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "actual_amount",
    },
    difference: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
  },
  primaryKey: ["id"],
  serverName: "shift_closure",
} as const;
const userTable = {
  name: "user",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    email: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    emailVerified: {
      type: "boolean",
      optional: true,
      customType: null as unknown as boolean,
      serverName: "email_verified",
    },
    image: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
    role: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
  },
  primaryKey: ["id"],
} as const;
const cashMovementRelationships = {
  organization: [
    {
      sourceField: ["organizationId"],
      destField: ["id"],
      destSchema: "organization",
      cardinality: "one",
    },
  ],
  shift: [
    {
      sourceField: ["shiftId"],
      destField: ["id"],
      destSchema: "shift",
      cardinality: "one",
    },
  ],
} as const;
const categoryRelationships = {
  organization: [
    {
      sourceField: ["organizationId"],
      destField: ["id"],
      destSchema: "organization",
      cardinality: "one",
    },
  ],
  products: [
    {
      sourceField: ["id"],
      destField: ["categoryId"],
      destSchema: "product",
      cardinality: "many",
    },
  ],
} as const;
const creditAccountRelationships = {
  organization: [
    {
      sourceField: ["organizationId"],
      destField: ["id"],
      destSchema: "organization",
      cardinality: "one",
    },
  ],
  customer: [
    {
      sourceField: ["customerId"],
      destField: ["id"],
      destSchema: "customer",
      cardinality: "one",
    },
  ],
  transactions: [
    {
      sourceField: ["id"],
      destField: ["creditAccountId"],
      destSchema: "creditTransaction",
      cardinality: "many",
    },
  ],
} as const;
const creditTransactionRelationships = {
  organization: [
    {
      sourceField: ["organizationId"],
      destField: ["id"],
      destSchema: "organization",
      cardinality: "one",
    },
  ],
  creditAccount: [
    {
      sourceField: ["creditAccountId"],
      destField: ["id"],
      destSchema: "creditAccount",
      cardinality: "one",
    },
  ],
  sale: [
    {
      sourceField: ["saleId"],
      destField: ["id"],
      destSchema: "sale",
      cardinality: "one",
    },
  ],
  payment: [
    {
      sourceField: ["paymentId"],
      destField: ["id"],
      destSchema: "payment",
      cardinality: "one",
    },
  ],
} as const;
const customerRelationships = {
  organization: [
    {
      sourceField: ["organizationId"],
      destField: ["id"],
      destSchema: "organization",
      cardinality: "one",
    },
  ],
  sales: [
    {
      sourceField: ["id"],
      destField: ["customerId"],
      destSchema: "sale",
      cardinality: "many",
    },
  ],
  creditAccount: [
    {
      sourceField: ["id"],
      destField: ["customerId"],
      destSchema: "creditAccount",
      cardinality: "one",
    },
  ],
} as const;
const inventoryMovementRelationships = {
  organization: [
    {
      sourceField: ["organizationId"],
      destField: ["id"],
      destSchema: "organization",
      cardinality: "one",
    },
  ],
  product: [
    {
      sourceField: ["productId"],
      destField: ["id"],
      destSchema: "product",
      cardinality: "one",
    },
  ],
  user: [
    {
      sourceField: ["userId"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
} as const;
const invitationRelationships = {
  organization: [
    {
      sourceField: ["organizationId"],
      destField: ["id"],
      destSchema: "organization",
      cardinality: "one",
    },
  ],
  user: [
    {
      sourceField: ["inviterId"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
} as const;
const memberRelationships = {
  organization: [
    {
      sourceField: ["organizationId"],
      destField: ["id"],
      destSchema: "organization",
      cardinality: "one",
    },
  ],
  user: [
    {
      sourceField: ["userId"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
} as const;
const organizationJoinLinkRelationships = {
  organization: [
    {
      sourceField: ["organizationId"],
      destField: ["id"],
      destSchema: "organization",
      cardinality: "one",
    },
  ],
} as const;
const organizationRelationships = {
  members: [
    {
      sourceField: ["id"],
      destField: ["organizationId"],
      destSchema: "member",
      cardinality: "many",
    },
  ],
  invitations: [
    {
      sourceField: ["id"],
      destField: ["organizationId"],
      destSchema: "invitation",
      cardinality: "many",
    },
  ],
  joinLinks: [
    {
      sourceField: ["id"],
      destField: ["organizationId"],
      destSchema: "organizationJoinLink",
      cardinality: "many",
    },
  ],
  customers: [
    {
      sourceField: ["id"],
      destField: ["organizationId"],
      destSchema: "customer",
      cardinality: "many",
    },
  ],
  categories: [
    {
      sourceField: ["id"],
      destField: ["organizationId"],
      destSchema: "category",
      cardinality: "many",
    },
  ],
  products: [
    {
      sourceField: ["id"],
      destField: ["organizationId"],
      destSchema: "product",
      cardinality: "many",
    },
  ],
  inventoryMovements: [
    {
      sourceField: ["id"],
      destField: ["organizationId"],
      destSchema: "inventoryMovement",
      cardinality: "many",
    },
  ],
  shifts: [
    {
      sourceField: ["id"],
      destField: ["organizationId"],
      destSchema: "shift",
      cardinality: "many",
    },
  ],
  cashMovements: [
    {
      sourceField: ["id"],
      destField: ["organizationId"],
      destSchema: "cashMovement",
      cardinality: "many",
    },
  ],
  sales: [
    {
      sourceField: ["id"],
      destField: ["organizationId"],
      destSchema: "sale",
      cardinality: "many",
    },
  ],
  payments: [
    {
      sourceField: ["id"],
      destField: ["organizationId"],
      destSchema: "payment",
      cardinality: "many",
    },
  ],
  creditAccounts: [
    {
      sourceField: ["id"],
      destField: ["organizationId"],
      destSchema: "creditAccount",
      cardinality: "many",
    },
  ],
  creditTransactions: [
    {
      sourceField: ["id"],
      destField: ["organizationId"],
      destSchema: "creditTransaction",
      cardinality: "many",
    },
  ],
} as const;
const paymentRelationships = {
  organization: [
    {
      sourceField: ["organizationId"],
      destField: ["id"],
      destSchema: "organization",
      cardinality: "one",
    },
  ],
  sale: [
    {
      sourceField: ["saleId"],
      destField: ["id"],
      destSchema: "sale",
      cardinality: "one",
    },
  ],
  shift: [
    {
      sourceField: ["shiftId"],
      destField: ["id"],
      destSchema: "shift",
      cardinality: "one",
    },
  ],
  creditTransactions: [
    {
      sourceField: ["id"],
      destField: ["paymentId"],
      destSchema: "creditTransaction",
      cardinality: "many",
    },
  ],
} as const;
const pedidoItemRelationships = {
  organization: [
    {
      sourceField: ["organizationId"],
      destField: ["id"],
      destSchema: "organization",
      cardinality: "one",
    },
  ],
  order: [
    {
      sourceField: ["orderId"],
      destField: ["id"],
      destSchema: "pedido",
      cardinality: "one",
    },
  ],
  product: [
    {
      sourceField: ["productId"],
      destField: ["id"],
      destSchema: "product",
      cardinality: "one",
    },
  ],
} as const;
const pedidoRelationships = {
  organization: [
    {
      sourceField: ["organizationId"],
      destField: ["id"],
      destSchema: "organization",
      cardinality: "one",
    },
  ],
  customer: [
    {
      sourceField: ["customerId"],
      destField: ["id"],
      destSchema: "customer",
      cardinality: "one",
    },
  ],
  sale: [
    {
      sourceField: ["saleId"],
      destField: ["id"],
      destSchema: "sale",
      cardinality: "one",
    },
  ],
  acceptedByUser: [
    {
      sourceField: ["acceptedByUserId"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
  items: [
    {
      sourceField: ["id"],
      destField: ["orderId"],
      destSchema: "pedidoItem",
      cardinality: "many",
    },
  ],
} as const;
const productRelationships = {
  organization: [
    {
      sourceField: ["organizationId"],
      destField: ["id"],
      destSchema: "organization",
      cardinality: "one",
    },
  ],
  category: [
    {
      sourceField: ["categoryId"],
      destField: ["id"],
      destSchema: "category",
      cardinality: "one",
    },
  ],
  inventoryMovements: [
    {
      sourceField: ["id"],
      destField: ["productId"],
      destSchema: "inventoryMovement",
      cardinality: "many",
    },
  ],
  saleItems: [
    {
      sourceField: ["id"],
      destField: ["productId"],
      destSchema: "saleItem",
      cardinality: "many",
    },
  ],
  modifierItems: [
    {
      sourceField: ["id"],
      destField: ["modifierProductId"],
      destSchema: "saleItemModifier",
      cardinality: "many",
    },
  ],
} as const;
const restaurantAreaRelationships = {
  organization: [
    {
      sourceField: ["organizationId"],
      destField: ["id"],
      destSchema: "organization",
      cardinality: "one",
    },
  ],
  tables: [
    {
      sourceField: ["id"],
      destField: ["areaId"],
      destSchema: "restaurantTable",
      cardinality: "many",
    },
  ],
} as const;
const restaurantKitchenTicketRelationships = {
  organization: [
    {
      sourceField: ["organizationId"],
      destField: ["id"],
      destSchema: "organization",
      cardinality: "one",
    },
  ],
  order: [
    {
      sourceField: ["orderId"],
      destField: ["id"],
      destSchema: "restaurantOrder",
      cardinality: "one",
    },
  ],
  createdByUser: [
    {
      sourceField: ["createdByUserId"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
  items: [
    {
      sourceField: ["id"],
      destField: ["kitchenTicketId"],
      destSchema: "restaurantOrderItem",
      cardinality: "many",
    },
  ],
} as const;
const restaurantOrderItemModifierRelationships = {
  organization: [
    {
      sourceField: ["organizationId"],
      destField: ["id"],
      destSchema: "organization",
      cardinality: "one",
    },
  ],
  orderItem: [
    {
      sourceField: ["orderItemId"],
      destField: ["id"],
      destSchema: "restaurantOrderItem",
      cardinality: "one",
    },
  ],
  modifierProduct: [
    {
      sourceField: ["modifierProductId"],
      destField: ["id"],
      destSchema: "product",
      cardinality: "one",
    },
  ],
} as const;
const restaurantOrderItemRelationships = {
  organization: [
    {
      sourceField: ["organizationId"],
      destField: ["id"],
      destSchema: "organization",
      cardinality: "one",
    },
  ],
  order: [
    {
      sourceField: ["orderId"],
      destField: ["id"],
      destSchema: "restaurantOrder",
      cardinality: "one",
    },
  ],
  kitchenTicket: [
    {
      sourceField: ["kitchenTicketId"],
      destField: ["id"],
      destSchema: "restaurantKitchenTicket",
      cardinality: "one",
    },
  ],
  product: [
    {
      sourceField: ["productId"],
      destField: ["id"],
      destSchema: "product",
      cardinality: "one",
    },
  ],
  modifiers: [
    {
      sourceField: ["id"],
      destField: ["orderItemId"],
      destSchema: "restaurantOrderItemModifier",
      cardinality: "many",
    },
  ],
} as const;
const restaurantOrderRelationships = {
  organization: [
    {
      sourceField: ["organizationId"],
      destField: ["id"],
      destSchema: "organization",
      cardinality: "one",
    },
  ],
  table: [
    {
      sourceField: ["tableId"],
      destField: ["id"],
      destSchema: "restaurantTable",
      cardinality: "one",
    },
  ],
  openedByUser: [
    {
      sourceField: ["openedByUserId"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
  closedByUser: [
    {
      sourceField: ["closedByUserId"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
  sale: [
    {
      sourceField: ["saleId"],
      destField: ["id"],
      destSchema: "sale",
      cardinality: "one",
    },
  ],
  items: [
    {
      sourceField: ["id"],
      destField: ["orderId"],
      destSchema: "restaurantOrderItem",
      cardinality: "many",
    },
  ],
  kitchenTickets: [
    {
      sourceField: ["id"],
      destField: ["orderId"],
      destSchema: "restaurantKitchenTicket",
      cardinality: "many",
    },
  ],
} as const;
const restaurantTableRelationships = {
  organization: [
    {
      sourceField: ["organizationId"],
      destField: ["id"],
      destSchema: "organization",
      cardinality: "one",
    },
  ],
  area: [
    {
      sourceField: ["areaId"],
      destField: ["id"],
      destSchema: "restaurantArea",
      cardinality: "one",
    },
  ],
  orders: [
    {
      sourceField: ["id"],
      destField: ["tableId"],
      destSchema: "restaurantOrder",
      cardinality: "many",
    },
  ],
} as const;
const saleItemModifierRelationships = {
  saleItem: [
    {
      sourceField: ["saleItemId"],
      destField: ["id"],
      destSchema: "saleItem",
      cardinality: "one",
    },
  ],
  organization: [
    {
      sourceField: ["organizationId"],
      destField: ["id"],
      destSchema: "organization",
      cardinality: "one",
    },
  ],
  modifierProduct: [
    {
      sourceField: ["modifierProductId"],
      destField: ["id"],
      destSchema: "product",
      cardinality: "one",
    },
  ],
} as const;
const saleItemRelationships = {
  sale: [
    {
      sourceField: ["saleId"],
      destField: ["id"],
      destSchema: "sale",
      cardinality: "one",
    },
  ],
  organization: [
    {
      sourceField: ["organizationId"],
      destField: ["id"],
      destSchema: "organization",
      cardinality: "one",
    },
  ],
  product: [
    {
      sourceField: ["productId"],
      destField: ["id"],
      destSchema: "product",
      cardinality: "one",
    },
  ],
  modifiers: [
    {
      sourceField: ["id"],
      destField: ["saleItemId"],
      destSchema: "saleItemModifier",
      cardinality: "many",
    },
  ],
} as const;
const saleRelationships = {
  organization: [
    {
      sourceField: ["organizationId"],
      destField: ["id"],
      destSchema: "organization",
      cardinality: "one",
    },
  ],
  shift: [
    {
      sourceField: ["shiftId"],
      destField: ["id"],
      destSchema: "shift",
      cardinality: "one",
    },
  ],
  customer: [
    {
      sourceField: ["customerId"],
      destField: ["id"],
      destSchema: "customer",
      cardinality: "one",
    },
  ],
  user: [
    {
      sourceField: ["userId"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
  items: [
    {
      sourceField: ["id"],
      destField: ["saleId"],
      destSchema: "saleItem",
      cardinality: "many",
    },
  ],
  payments: [
    {
      sourceField: ["id"],
      destField: ["saleId"],
      destSchema: "payment",
      cardinality: "many",
    },
  ],
  creditTransactions: [
    {
      sourceField: ["id"],
      destField: ["saleId"],
      destSchema: "creditTransaction",
      cardinality: "many",
    },
  ],
} as const;
const shiftClosureRelationships = {
  shift: [
    {
      sourceField: ["shiftId"],
      destField: ["id"],
      destSchema: "shift",
      cardinality: "one",
    },
  ],
} as const;
const shiftRelationships = {
  organization: [
    {
      sourceField: ["organizationId"],
      destField: ["id"],
      destSchema: "organization",
      cardinality: "one",
    },
  ],
  user: [
    {
      sourceField: ["userId"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
  cashMovements: [
    {
      sourceField: ["id"],
      destField: ["shiftId"],
      destSchema: "cashMovement",
      cardinality: "many",
    },
  ],
  closures: [
    {
      sourceField: ["id"],
      destField: ["shiftId"],
      destSchema: "shiftClosure",
      cardinality: "many",
    },
  ],
  sales: [
    {
      sourceField: ["id"],
      destField: ["shiftId"],
      destSchema: "sale",
      cardinality: "many",
    },
  ],
  payments: [
    {
      sourceField: ["id"],
      destField: ["shiftId"],
      destSchema: "payment",
      cardinality: "many",
    },
  ],
} as const;
/**
 * The Zero schema object.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const schema = {
  tables: {
    cashMovement: cashMovementTable,
    category: categoryTable,
    creditAccount: creditAccountTable,
    creditTransaction: creditTransactionTable,
    customer: customerTable,
    inventoryMovement: inventoryMovementTable,
    invitation: invitationTable,
    member: memberTable,
    organization: organizationTable,
    organizationJoinLink: organizationJoinLinkTable,
    organizationModuleEntitlement: organizationModuleEntitlementTable,
    payment: paymentTable,
    pedido: pedidoTable,
    pedidoItem: pedidoItemTable,
    product: productTable,
    restaurantArea: restaurantAreaTable,
    restaurantKitchenTicket: restaurantKitchenTicketTable,
    restaurantOrder: restaurantOrderTable,
    restaurantOrderItem: restaurantOrderItemTable,
    restaurantOrderItemModifier: restaurantOrderItemModifierTable,
    restaurantTable: restaurantTable,
    sale: saleTable,
    saleItem: saleItemTable,
    saleItemModifier: saleItemModifierTable,
    shift: shiftTable,
    shiftClosure: shiftClosureTable,
    user: userTable,
  },
  relationships: {
    cashMovement: cashMovementRelationships,
    category: categoryRelationships,
    creditAccount: creditAccountRelationships,
    creditTransaction: creditTransactionRelationships,
    customer: customerRelationships,
    inventoryMovement: inventoryMovementRelationships,
    invitation: invitationRelationships,
    member: memberRelationships,
    organizationJoinLink: organizationJoinLinkRelationships,
    organization: organizationRelationships,
    payment: paymentRelationships,
    pedidoItem: pedidoItemRelationships,
    pedido: pedidoRelationships,
    product: productRelationships,
    restaurantArea: restaurantAreaRelationships,
    restaurantKitchenTicket: restaurantKitchenTicketRelationships,
    restaurantOrderItemModifier: restaurantOrderItemModifierRelationships,
    restaurantOrderItem: restaurantOrderItemRelationships,
    restaurantOrder: restaurantOrderRelationships,
    restaurantTable: restaurantTableRelationships,
    saleItemModifier: saleItemModifierRelationships,
    saleItem: saleItemRelationships,
    sale: saleRelationships,
    shiftClosure: shiftClosureRelationships,
    shift: shiftRelationships,
  },
  enableLegacyQueries: false,
  enableLegacyMutators: false,
} as const;

/**
 * Represents the Zero schema type.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Schema = typeof schema;
/**
 * Represents a row from the "cashMovement" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type CashMovement = Row<(typeof schema)["tables"]["cashMovement"]>;
/**
 * Represents a row from the "category" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Category = Row<(typeof schema)["tables"]["category"]>;
/**
 * Represents a row from the "creditAccount" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type CreditAccount = Row<(typeof schema)["tables"]["creditAccount"]>;
/**
 * Represents a row from the "creditTransaction" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type CreditTransaction = Row<
  (typeof schema)["tables"]["creditTransaction"]
>;
/**
 * Represents a row from the "customer" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Customer = Row<(typeof schema)["tables"]["customer"]>;
/**
 * Represents a row from the "inventoryMovement" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type InventoryMovement = Row<
  (typeof schema)["tables"]["inventoryMovement"]
>;
/**
 * Represents a row from the "invitation" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Invitation = Row<(typeof schema)["tables"]["invitation"]>;
/**
 * Represents a row from the "member" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Member = Row<(typeof schema)["tables"]["member"]>;
/**
 * Represents a row from the "organization" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Organization = Row<(typeof schema)["tables"]["organization"]>;
/**
 * Represents a row from the "organizationJoinLink" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type OrganizationJoinLink = Row<
  (typeof schema)["tables"]["organizationJoinLink"]
>;
/**
 * Represents a row from the "organizationModuleEntitlement" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type OrganizationModuleEntitlement = Row<
  (typeof schema)["tables"]["organizationModuleEntitlement"]
>;
/**
 * Represents a row from the "payment" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Payment = Row<(typeof schema)["tables"]["payment"]>;
/**
 * Represents a row from the "pedido" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Pedido = Row<(typeof schema)["tables"]["pedido"]>;
/**
 * Represents a row from the "pedidoItem" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type PedidoItem = Row<(typeof schema)["tables"]["pedidoItem"]>;
/**
 * Represents a row from the "product" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Product = Row<(typeof schema)["tables"]["product"]>;
/**
 * Represents a row from the "restaurantArea" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type RestaurantArea = Row<(typeof schema)["tables"]["restaurantArea"]>;
/**
 * Represents a row from the "restaurantKitchenTicket" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type RestaurantKitchenTicket = Row<
  (typeof schema)["tables"]["restaurantKitchenTicket"]
>;
/**
 * Represents a row from the "restaurantOrder" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type RestaurantOrder = Row<(typeof schema)["tables"]["restaurantOrder"]>;
/**
 * Represents a row from the "restaurantOrderItem" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type RestaurantOrderItem = Row<
  (typeof schema)["tables"]["restaurantOrderItem"]
>;
/**
 * Represents a row from the "restaurantOrderItemModifier" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type RestaurantOrderItemModifier = Row<
  (typeof schema)["tables"]["restaurantOrderItemModifier"]
>;
/**
 * Represents a row from the "restaurantTable" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type RestaurantTable = Row<(typeof schema)["tables"]["restaurantTable"]>;
/**
 * Represents a row from the "sale" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Sale = Row<(typeof schema)["tables"]["sale"]>;
/**
 * Represents a row from the "saleItem" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type SaleItem = Row<(typeof schema)["tables"]["saleItem"]>;
/**
 * Represents a row from the "saleItemModifier" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type SaleItemModifier = Row<
  (typeof schema)["tables"]["saleItemModifier"]
>;
/**
 * Represents a row from the "shift" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Shift = Row<(typeof schema)["tables"]["shift"]>;
/**
 * Represents a row from the "shiftClosure" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type ShiftClosure = Row<(typeof schema)["tables"]["shiftClosure"]>;
/**
 * Represents a row from the "user" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type User = Row<(typeof schema)["tables"]["user"]>;

/**
 * Represents the ZQL query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const zql = createBuilder(schema);
/**
 * Represents the Zero schema query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const builder = zql;

/** Defines the default types for Zero */
declare module "@rocicorp/zero" {
  interface DefaultTypes {
    schema: Schema;
  }
}
